// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Duke1616/eiam/internal/event/audit (interfaces: IAuditProducer)
//
// Generated by this command:
//
//	mockgen -package=auditmocks -destination=./mocks/producer.mock.go github.com/Duke1616/eiam/internal/event/audit IAuditProducer
//

// Package auditmocks is a generated GoMock package.
package auditmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eiam/internal/domain"
	audit "github.com/Duke1616/eiam/internal/event/audit"
	gomock "go.uber.org/mock/gomock"
)

// MockIAuditProducer is a mock of IAuditProducer interface.
type MockIAuditProducer struct {
	ctrl     *gomock.Controller
	recorder *MockIAuditProducerMockRecorder
	isgomock struct{}
}

// MockIAuditProducerMockRecorder is the mock recorder for MockIAuditProducer.
type MockIAuditProducerMockRecorder struct {
	mock *MockIAuditProducer
}

// NewMockIAuditProducer creates a new mock instance.
func NewMockIAuditProducer(ctrl *gomock.Controller) *MockIAuditProducer {
	mock := &MockIAuditProducer{ctrl: ctrl}
	mock.recorder = &MockIAuditProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuditProducer) EXPECT() *MockIAuditProducerMockRecorder {
	return m.recorder
}

// Produce mocks base method.
func (m *MockIAuditProducer) Produce(ctx context.Context, evt audit.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", ctx, evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockIAuditProducerMockRecorder) Produce(ctx, evt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockIAuditProducer)(nil).Produce), ctx, evt)
}

// RecordAuth mocks base method.
func (m *MockIAuditProducer) RecordAuth(ctx context.Context, log domain.AuthLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordAuth", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordAuth indicates an expected call of RecordAuth.
func (mr *MockIAuditProducerMockRecorder) RecordAuth(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordAuth", reflect.TypeOf((*MockIAuditProducer)(nil).RecordAuth), ctx, log)
}

// RecordOperation mocks base method.
func (m *MockIAuditProducer) RecordOperation(ctx context.Context, log domain.OperationLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordOperation", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordOperation indicates an expected call of RecordOperation.
func (mr *MockIAuditProducerMockRecorder) RecordOperation(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordOperation", reflect.TypeOf((*MockIAuditProducer)(nil).RecordOperation), ctx, log)
}
