// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Duke1616/eiam/internal/repository (interfaces: IAuditRepository)
//
// Generated by this command:
//
//	mockgen -package=repomocks -destination=./mocks/audit.mock.go github.com/Duke1616/eiam/internal/repository IAuditRepository
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eiam/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIAuditRepository is a mock of IAuditRepository interface.
type MockIAuditRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAuditRepositoryMockRecorder
	isgomock struct{}
}

// MockIAuditRepositoryMockRecorder is the mock recorder for MockIAuditRepository.
type MockIAuditRepositoryMockRecorder struct {
	mock *MockIAuditRepository
}

// NewMockIAuditRepository creates a new mock instance.
func NewMockIAuditRepository(ctrl *gomock.Controller) *MockIAuditRepository {
	mock := &MockIAuditRepository{ctrl: ctrl}
	mock.recorder = &MockIAuditRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuditRepository) EXPECT() *MockIAuditRepositoryMockRecorder {
	return m.recorder
}

// BatchSaveAuthLogs mocks base method.
func (m *MockIAuditRepository) BatchSaveAuthLogs(ctx context.Context, logs []domain.AuthLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchSaveAuthLogs", ctx, logs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchSaveAuthLogs indicates an expected call of BatchSaveAuthLogs.
func (mr *MockIAuditRepositoryMockRecorder) BatchSaveAuthLogs(ctx, logs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchSaveAuthLogs", reflect.TypeOf((*MockIAuditRepository)(nil).BatchSaveAuthLogs), ctx, logs)
}

// BatchSaveOperationLogs mocks base method.
func (m *MockIAuditRepository) BatchSaveOperationLogs(ctx context.Context, logs []domain.OperationLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchSaveOperationLogs", ctx, logs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchSaveOperationLogs indicates an expected call of BatchSaveOperationLogs.
func (mr *MockIAuditRepositoryMockRecorder) BatchSaveOperationLogs(ctx, logs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchSaveOperationLogs", reflect.TypeOf((*MockIAuditRepository)(nil).BatchSaveOperationLogs), ctx, logs)
}

// ListAuthLogs mocks base method.
func (m *MockIAuditRepository) ListAuthLogs(ctx context.Context, filter domain.AuthLogFilter, offset, limit int) ([]domain.AuthLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuthLogs", ctx, filter, offset, limit)
	ret0, _ := ret[0].([]domain.AuthLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAuthLogs indicates an expected call of ListAuthLogs.
func (mr *MockIAuditRepositoryMockRecorder) ListAuthLogs(ctx, filter, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuthLogs", reflect.TypeOf((*MockIAuditRepository)(nil).ListAuthLogs), ctx, filter, offset, limit)
}

// ListOperationLogs mocks base method.
func (m *MockIAuditRepository) ListOperationLogs(ctx context.Context, filter domain.OperationLogFilter, offset, limit int) ([]domain.OperationLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOperationLogs", ctx, filter, offset, limit)
	ret0, _ := ret[0].([]domain.OperationLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListOperationLogs indicates an expected call of ListOperationLogs.
func (mr *MockIAuditRepositoryMockRecorder) ListOperationLogs(ctx, filter, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOperationLogs", reflect.TypeOf((*MockIAuditRepository)(nil).ListOperationLogs), ctx, filter, offset, limit)
}
