// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Duke1616/eiam/internal/repository (interfaces: IPermissionRepository)
//
// Generated by this command:
//
//	mockgen -package=repomocks -destination=./mocks/permission.mock.go github.com/Duke1616/eiam/internal/repository IPermissionRepository
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eiam/internal/domain"
	dao "github.com/Duke1616/eiam/internal/repository/dao"
	gomock "go.uber.org/mock/gomock"
)

// MockIPermissionRepository is a mock of IPermissionRepository interface.
type MockIPermissionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPermissionRepositoryMockRecorder
	isgomock struct{}
}

// MockIPermissionRepositoryMockRecorder is the mock recorder for MockIPermissionRepository.
type MockIPermissionRepositoryMockRecorder struct {
	mock *MockIPermissionRepository
}

// NewMockIPermissionRepository creates a new mock instance.
func NewMockIPermissionRepository(ctrl *gomock.Controller) *MockIPermissionRepository {
	mock := &MockIPermissionRepository{ctrl: ctrl}
	mock.recorder = &MockIPermissionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPermissionRepository) EXPECT() *MockIPermissionRepositoryMockRecorder {
	return m.recorder
}

// BatchBindResources mocks base method.
func (m *MockIPermissionRepository) BatchBindResources(ctx context.Context, bindings map[string][]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchBindResources", ctx, bindings)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchBindResources indicates an expected call of BatchBindResources.
func (mr *MockIPermissionRepositoryMockRecorder) BatchBindResources(ctx, bindings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchBindResources", reflect.TypeOf((*MockIPermissionRepository)(nil).BatchBindResources), ctx, bindings)
}

// BatchCreatePermission mocks base method.
func (m *MockIPermissionRepository) BatchCreatePermission(ctx context.Context, perms []domain.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreatePermission", ctx, perms)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreatePermission indicates an expected call of BatchCreatePermission.
func (mr *MockIPermissionRepositoryMockRecorder) BatchCreatePermission(ctx, perms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreatePermission", reflect.TypeOf((*MockIPermissionRepository)(nil).BatchCreatePermission), ctx, perms)
}

// BindResources mocks base method.
func (m *MockIPermissionRepository) BindResources(ctx context.Context, permId int64, permCode string, resURNs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindResources", ctx, permId, permCode, resURNs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BindResources indicates an expected call of BindResources.
func (mr *MockIPermissionRepositoryMockRecorder) BindResources(ctx, permId, permCode, resURNs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindResources", reflect.TypeOf((*MockIPermissionRepository)(nil).BindResources), ctx, permId, permCode, resURNs)
}

// ClearAllPermissionCaches mocks base method.
func (m *MockIPermissionRepository) ClearAllPermissionCaches(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearAllPermissionCaches", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearAllPermissionCaches indicates an expected call of ClearAllPermissionCaches.
func (mr *MockIPermissionRepositoryMockRecorder) ClearAllPermissionCaches(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearAllPermissionCaches", reflect.TypeOf((*MockIPermissionRepository)(nil).ClearAllPermissionCaches), ctx)
}

// CountByService mocks base method.
func (m *MockIPermissionRepository) CountByService(ctx context.Context) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByService", ctx)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByService indicates an expected call of CountByService.
func (mr *MockIPermissionRepositoryMockRecorder) CountByService(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByService", reflect.TypeOf((*MockIPermissionRepository)(nil).CountByService), ctx)
}

// CreatePermission mocks base method.
func (m *MockIPermissionRepository) CreatePermission(ctx context.Context, p domain.Permission) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePermission", ctx, p)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePermission indicates an expected call of CreatePermission.
func (mr *MockIPermissionRepositoryMockRecorder) CreatePermission(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePermission", reflect.TypeOf((*MockIPermissionRepository)(nil).CreatePermission), ctx, p)
}

// DeletePermission mocks base method.
func (m *MockIPermissionRepository) DeletePermission(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePermission", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePermission indicates an expected call of DeletePermission.
func (mr *MockIPermissionRepositoryMockRecorder) DeletePermission(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePermission", reflect.TypeOf((*MockIPermissionRepository)(nil).DeletePermission), ctx, id)
}

// DeletePermissionsByServiceAndCodes mocks base method.
func (m *MockIPermissionRepository) DeletePermissionsByServiceAndCodes(ctx context.Context, service, source string, codes []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePermissionsByServiceAndCodes", ctx, service, source, codes)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePermissionsByServiceAndCodes indicates an expected call of DeletePermissionsByServiceAndCodes.
func (mr *MockIPermissionRepositoryMockRecorder) DeletePermissionsByServiceAndCodes(ctx, service, source, codes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePermissionsByServiceAndCodes", reflect.TypeOf((*MockIPermissionRepository)(nil).DeletePermissionsByServiceAndCodes), ctx, service, source, codes)
}

// FindBindingsByPerm mocks base method.
func (m *MockIPermissionRepository) FindBindingsByPerm(ctx context.Context, permId int64) ([]domain.ResourceBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBindingsByPerm", ctx, permId)
	ret0, _ := ret[0].([]domain.ResourceBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBindingsByPerm indicates an expected call of FindBindingsByPerm.
func (mr *MockIPermissionRepositoryMockRecorder) FindBindingsByPerm(ctx, permId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBindingsByPerm", reflect.TypeOf((*MockIPermissionRepository)(nil).FindBindingsByPerm), ctx, permId)
}

// FindByActions mocks base method.
func (m *MockIPermissionRepository) FindByActions(ctx context.Context, actions []string) ([]domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByActions", ctx, actions)
	ret0, _ := ret[0].([]domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByActions indicates an expected call of FindByActions.
func (mr *MockIPermissionRepositoryMockRecorder) FindByActions(ctx, actions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByActions", reflect.TypeOf((*MockIPermissionRepository)(nil).FindByActions), ctx, actions)
}

// FindCodesByResource mocks base method.
func (m *MockIPermissionRepository) FindCodesByResource(ctx context.Context, resURN string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCodesByResource", ctx, resURN)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCodesByResource indicates an expected call of FindCodesByResource.
func (mr *MockIPermissionRepositoryMockRecorder) FindCodesByResource(ctx, resURN any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCodesByResource", reflect.TypeOf((*MockIPermissionRepository)(nil).FindCodesByResource), ctx, resURN)
}

// FindCodesByResourceURNs mocks base method.
func (m *MockIPermissionRepository) FindCodesByResourceURNs(ctx context.Context, resURNs []string) (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCodesByResourceURNs", ctx, resURNs)
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCodesByResourceURNs indicates an expected call of FindCodesByResourceURNs.
func (mr *MockIPermissionRepositoryMockRecorder) FindCodesByResourceURNs(ctx, resURNs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCodesByResourceURNs", reflect.TypeOf((*MockIPermissionRepository)(nil).FindCodesByResourceURNs), ctx, resURNs)
}

// FindParentsByNeeds mocks base method.
func (m *MockIPermissionRepository) FindParentsByNeeds(ctx context.Context, codes []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindParentsByNeeds", ctx, codes)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindParentsByNeeds indicates an expected call of FindParentsByNeeds.
func (mr *MockIPermissionRepositoryMockRecorder) FindParentsByNeeds(ctx, codes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindParentsByNeeds", reflect.TypeOf((*MockIPermissionRepository)(nil).FindParentsByNeeds), ctx, codes)
}

// GetByCode mocks base method.
func (m *MockIPermissionRepository) GetByCode(ctx context.Context, code string) (domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockIPermissionRepositoryMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockIPermissionRepository)(nil).GetByCode), ctx, code)
}

// GetManifest mocks base method.
func (m *MockIPermissionRepository) GetManifest(ctx context.Context, isSystem bool) (domain.PermissionManifest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManifest", ctx, isSystem)
	ret0, _ := ret[0].(domain.PermissionManifest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetManifest indicates an expected call of GetManifest.
func (mr *MockIPermissionRepositoryMockRecorder) GetManifest(ctx, isSystem any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManifest", reflect.TypeOf((*MockIPermissionRepository)(nil).GetManifest), ctx, isSystem)
}

// GetMenuBindings mocks base method.
func (m *MockIPermissionRepository) GetMenuBindings(ctx context.Context) (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenuBindings", ctx)
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenuBindings indicates an expected call of GetMenuBindings.
func (mr *MockIPermissionRepositoryMockRecorder) GetMenuBindings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenuBindings", reflect.TypeOf((*MockIPermissionRepository)(nil).GetMenuBindings), ctx)
}

// ListAllPermissions mocks base method.
func (m *MockIPermissionRepository) ListAllPermissions(ctx context.Context) ([]domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllPermissions", ctx)
	ret0, _ := ret[0].([]domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllPermissions indicates an expected call of ListAllPermissions.
func (mr *MockIPermissionRepositoryMockRecorder) ListAllPermissions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllPermissions", reflect.TypeOf((*MockIPermissionRepository)(nil).ListAllPermissions), ctx)
}

// ListCasbinRules mocks base method.
func (m *MockIPermissionRepository) ListCasbinRules(ctx context.Context, tid, offset, limit int64, v0Prefix, v1Prefix, keyword string) ([]dao.CasbinRule, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCasbinRules", ctx, tid, offset, limit, v0Prefix, v1Prefix, keyword)
	ret0, _ := ret[0].([]dao.CasbinRule)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCasbinRules indicates an expected call of ListCasbinRules.
func (mr *MockIPermissionRepositoryMockRecorder) ListCasbinRules(ctx, tid, offset, limit, v0Prefix, v1Prefix, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCasbinRules", reflect.TypeOf((*MockIPermissionRepository)(nil).ListCasbinRules), ctx, tid, offset, limit, v0Prefix, v1Prefix, keyword)
}

// MarkPermissionsAsOrphan mocks base method.
func (m *MockIPermissionRepository) MarkPermissionsAsOrphan(ctx context.Context, service, source string, codes []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPermissionsAsOrphan", ctx, service, source, codes)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPermissionsAsOrphan indicates an expected call of MarkPermissionsAsOrphan.
func (mr *MockIPermissionRepositoryMockRecorder) MarkPermissionsAsOrphan(ctx, service, source, codes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPermissionsAsOrphan", reflect.TypeOf((*MockIPermissionRepository)(nil).MarkPermissionsAsOrphan), ctx, service, source, codes)
}

// PhysicalClearService mocks base method.
func (m *MockIPermissionRepository) PhysicalClearService(ctx context.Context, service, source string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PhysicalClearService", ctx, service, source)
	ret0, _ := ret[0].(error)
	return ret0
}

// PhysicalClearService indicates an expected call of PhysicalClearService.
func (mr *MockIPermissionRepositoryMockRecorder) PhysicalClearService(ctx, service, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PhysicalClearService", reflect.TypeOf((*MockIPermissionRepository)(nil).PhysicalClearService), ctx, service, source)
}

// SetManifest mocks base method.
func (m *MockIPermissionRepository) SetManifest(ctx context.Context, isSystem bool, manifest domain.PermissionManifest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetManifest", ctx, isSystem, manifest)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetManifest indicates an expected call of SetManifest.
func (mr *MockIPermissionRepositoryMockRecorder) SetManifest(ctx, isSystem, manifest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetManifest", reflect.TypeOf((*MockIPermissionRepository)(nil).SetManifest), ctx, isSystem, manifest)
}

// SyncPermissions mocks base method.
func (m *MockIPermissionRepository) SyncPermissions(ctx context.Context, service, source string, perms []domain.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncPermissions", ctx, service, source, perms)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncPermissions indicates an expected call of SyncPermissions.
func (mr *MockIPermissionRepositoryMockRecorder) SyncPermissions(ctx, service, source, perms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncPermissions", reflect.TypeOf((*MockIPermissionRepository)(nil).SyncPermissions), ctx, service, source, perms)
}

// SyncResourceBindings mocks base method.
func (m *MockIPermissionRepository) SyncResourceBindings(ctx context.Context, allURNs []string, mappings map[string][]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncResourceBindings", ctx, allURNs, mappings)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncResourceBindings indicates an expected call of SyncResourceBindings.
func (mr *MockIPermissionRepositoryMockRecorder) SyncResourceBindings(ctx, allURNs, mappings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncResourceBindings", reflect.TypeOf((*MockIPermissionRepository)(nil).SyncResourceBindings), ctx, allURNs, mappings)
}

// Transaction mocks base method.
func (m *MockIPermissionRepository) Transaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockIPermissionRepositoryMockRecorder) Transaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockIPermissionRepository)(nil).Transaction), ctx, fn)
}
