// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Duke1616/eiam/internal/repository (interfaces: IResourceRepository)
//
// Generated by this command:
//
//	mockgen -package=repomocks -destination=./mocks/resource.mock.go github.com/Duke1616/eiam/internal/repository IResourceRepository
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eiam/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIResourceRepository is a mock of IResourceRepository interface.
type MockIResourceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIResourceRepositoryMockRecorder
	isgomock struct{}
}

// MockIResourceRepositoryMockRecorder is the mock recorder for MockIResourceRepository.
type MockIResourceRepositoryMockRecorder struct {
	mock *MockIResourceRepository
}

// NewMockIResourceRepository creates a new mock instance.
func NewMockIResourceRepository(ctrl *gomock.Controller) *MockIResourceRepository {
	mock := &MockIResourceRepository{ctrl: ctrl}
	mock.recorder = &MockIResourceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIResourceRepository) EXPECT() *MockIResourceRepositoryMockRecorder {
	return m.recorder
}

// BatchCreateAPI mocks base method.
func (m *MockIResourceRepository) BatchCreateAPI(ctx context.Context, apis []domain.API) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreateAPI", ctx, apis)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreateAPI indicates an expected call of BatchCreateAPI.
func (mr *MockIResourceRepositoryMockRecorder) BatchCreateAPI(ctx, apis any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreateAPI", reflect.TypeOf((*MockIResourceRepository)(nil).BatchCreateAPI), ctx, apis)
}

// BatchUpdateMenuSort mocks base method.
func (m *MockIResourceRepository) BatchUpdateMenuSort(ctx context.Context, menus []domain.Menu) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdateMenuSort", ctx, menus)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdateMenuSort indicates an expected call of BatchUpdateMenuSort.
func (mr *MockIResourceRepositoryMockRecorder) BatchUpdateMenuSort(ctx, menus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdateMenuSort", reflect.TypeOf((*MockIResourceRepository)(nil).BatchUpdateMenuSort), ctx, menus)
}

// CreateAPI mocks base method.
func (m *MockIResourceRepository) CreateAPI(ctx context.Context, a domain.API) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAPI", ctx, a)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAPI indicates an expected call of CreateAPI.
func (mr *MockIResourceRepositoryMockRecorder) CreateAPI(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAPI", reflect.TypeOf((*MockIResourceRepository)(nil).CreateAPI), ctx, a)
}

// DeleteAPIsByServiceAndURNs mocks base method.
func (m *MockIResourceRepository) DeleteAPIsByServiceAndURNs(ctx context.Context, service, source string, urns []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAPIsByServiceAndURNs", ctx, service, source, urns)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAPIsByServiceAndURNs indicates an expected call of DeleteAPIsByServiceAndURNs.
func (mr *MockIResourceRepositoryMockRecorder) DeleteAPIsByServiceAndURNs(ctx, service, source, urns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAPIsByServiceAndURNs", reflect.TypeOf((*MockIResourceRepository)(nil).DeleteAPIsByServiceAndURNs), ctx, service, source, urns)
}

// FindAPIByPath mocks base method.
func (m *MockIResourceRepository) FindAPIByPath(ctx context.Context, service, method, path string) (domain.API, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAPIByPath", ctx, service, method, path)
	ret0, _ := ret[0].(domain.API)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAPIByPath indicates an expected call of FindAPIByPath.
func (mr *MockIResourceRepositoryMockRecorder) FindAPIByPath(ctx, service, method, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAPIByPath", reflect.TypeOf((*MockIResourceRepository)(nil).FindAPIByPath), ctx, service, method, path)
}

// GetMenu mocks base method.
func (m *MockIResourceRepository) GetMenu(ctx context.Context, id int64) (domain.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenu", ctx, id)
	ret0, _ := ret[0].(domain.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenu indicates an expected call of GetMenu.
func (mr *MockIResourceRepositoryMockRecorder) GetMenu(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenu", reflect.TypeOf((*MockIResourceRepository)(nil).GetMenu), ctx, id)
}

// ListAPIsByService mocks base method.
func (m *MockIResourceRepository) ListAPIsByService(ctx context.Context, service string) ([]domain.API, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAPIsByService", ctx, service)
	ret0, _ := ret[0].([]domain.API)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAPIsByService indicates an expected call of ListAPIsByService.
func (mr *MockIResourceRepositoryMockRecorder) ListAPIsByService(ctx, service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAPIsByService", reflect.TypeOf((*MockIResourceRepository)(nil).ListAPIsByService), ctx, service)
}

// ListAllAPIs mocks base method.
func (m *MockIResourceRepository) ListAllAPIs(ctx context.Context) ([]domain.API, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllAPIs", ctx)
	ret0, _ := ret[0].([]domain.API)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllAPIs indicates an expected call of ListAllAPIs.
func (mr *MockIResourceRepositoryMockRecorder) ListAllAPIs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllAPIs", reflect.TypeOf((*MockIResourceRepository)(nil).ListAllAPIs), ctx)
}

// ListAllMenus mocks base method.
func (m *MockIResourceRepository) ListAllMenus(ctx context.Context) ([]domain.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllMenus", ctx)
	ret0, _ := ret[0].([]domain.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllMenus indicates an expected call of ListAllMenus.
func (mr *MockIResourceRepositoryMockRecorder) ListAllMenus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllMenus", reflect.TypeOf((*MockIResourceRepository)(nil).ListAllMenus), ctx)
}

// ListMenusByParentID mocks base method.
func (m *MockIResourceRepository) ListMenusByParentID(ctx context.Context, parentID int64) ([]domain.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMenusByParentID", ctx, parentID)
	ret0, _ := ret[0].([]domain.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMenusByParentID indicates an expected call of ListMenusByParentID.
func (mr *MockIResourceRepositoryMockRecorder) ListMenusByParentID(ctx, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMenusByParentID", reflect.TypeOf((*MockIResourceRepository)(nil).ListMenusByParentID), ctx, parentID)
}

// MarkAPIsAsOrphan mocks base method.
func (m *MockIResourceRepository) MarkAPIsAsOrphan(ctx context.Context, service, source string, urns []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAPIsAsOrphan", ctx, service, source, urns)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAPIsAsOrphan indicates an expected call of MarkAPIsAsOrphan.
func (mr *MockIResourceRepositoryMockRecorder) MarkAPIsAsOrphan(ctx, service, source, urns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAPIsAsOrphan", reflect.TypeOf((*MockIResourceRepository)(nil).MarkAPIsAsOrphan), ctx, service, source, urns)
}

// SyncAPIs mocks base method.
func (m *MockIResourceRepository) SyncAPIs(ctx context.Context, service, source string, apis []domain.API) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncAPIs", ctx, service, source, apis)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncAPIs indicates an expected call of SyncAPIs.
func (mr *MockIResourceRepositoryMockRecorder) SyncAPIs(ctx, service, source, apis any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncAPIs", reflect.TypeOf((*MockIResourceRepository)(nil).SyncAPIs), ctx, service, source, apis)
}

// SyncMenus mocks base method.
func (m *MockIResourceRepository) SyncMenus(ctx context.Context, menus domain.MenuList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncMenus", ctx, menus)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncMenus indicates an expected call of SyncMenus.
func (mr *MockIResourceRepositoryMockRecorder) SyncMenus(ctx, menus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncMenus", reflect.TypeOf((*MockIResourceRepository)(nil).SyncMenus), ctx, menus)
}

// UpdateMenuSort mocks base method.
func (m *MockIResourceRepository) UpdateMenuSort(ctx context.Context, id, parentID, sortKey int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMenuSort", ctx, id, parentID, sortKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMenuSort indicates an expected call of UpdateMenuSort.
func (mr *MockIResourceRepositoryMockRecorder) UpdateMenuSort(ctx, id, parentID, sortKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMenuSort", reflect.TypeOf((*MockIResourceRepository)(nil).UpdateMenuSort), ctx, id, parentID, sortKey)
}

// UpsertMenu mocks base method.
func (m_2 *MockIResourceRepository) UpsertMenu(ctx context.Context, m *domain.Menu) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpsertMenu", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertMenu indicates an expected call of UpsertMenu.
func (mr *MockIResourceRepositoryMockRecorder) UpsertMenu(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertMenu", reflect.TypeOf((*MockIResourceRepository)(nil).UpsertMenu), ctx, m)
}
