// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Duke1616/eiam/internal/repository (interfaces: IUserRepository)
//
// Generated by this command:
//
//	mockgen -package=repomocks -destination=./mocks/user.mock.go github.com/Duke1616/eiam/internal/repository IUserRepository
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eiam/internal/domain"
	webauthn "github.com/go-webauthn/webauthn/webauthn"
	gomock "go.uber.org/mock/gomock"
)

// MockIUserRepository is a mock of IUserRepository interface.
type MockIUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIUserRepositoryMockRecorder
	isgomock struct{}
}

// MockIUserRepositoryMockRecorder is the mock recorder for MockIUserRepository.
type MockIUserRepositoryMockRecorder struct {
	mock *MockIUserRepository
}

// NewMockIUserRepository creates a new mock instance.
func NewMockIUserRepository(ctrl *gomock.Controller) *MockIUserRepository {
	mock := &MockIUserRepository{ctrl: ctrl}
	mock.recorder = &MockIUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserRepository) EXPECT() *MockIUserRepositoryMockRecorder {
	return m.recorder
}

// BatchDelete mocks base method.
func (m *MockIUserRepository) BatchDelete(ctx context.Context, ids []int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ctx, ids)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockIUserRepositoryMockRecorder) BatchDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockIUserRepository)(nil).BatchDelete), ctx, ids)
}

// BatchUpsert mocks base method.
func (m *MockIUserRepository) BatchUpsert(ctx context.Context, users []domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpsert", ctx, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpsert indicates an expected call of BatchUpsert.
func (mr *MockIUserRepositoryMockRecorder) BatchUpsert(ctx, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpsert", reflect.TypeOf((*MockIUserRepository)(nil).BatchUpsert), ctx, users)
}

// CheckUsersExist mocks base method.
func (m *MockIUserRepository) CheckUsersExist(ctx context.Context, usernames []string) (map[string]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUsersExist", ctx, usernames)
	ret0, _ := ret[0].(map[string]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUsersExist indicates an expected call of CheckUsersExist.
func (mr *MockIUserRepositoryMockRecorder) CheckUsersExist(ctx, usernames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUsersExist", reflect.TypeOf((*MockIUserRepository)(nil).CheckUsersExist), ctx, usernames)
}

// ClearFailedAttempts mocks base method.
func (m *MockIUserRepository) ClearFailedAttempts(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearFailedAttempts", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearFailedAttempts indicates an expected call of ClearFailedAttempts.
func (mr *MockIUserRepositoryMockRecorder) ClearFailedAttempts(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearFailedAttempts", reflect.TypeOf((*MockIUserRepository)(nil).ClearFailedAttempts), ctx, username)
}

// Count mocks base method.
func (m *MockIUserRepository) Count(ctx context.Context, keyword string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, keyword)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockIUserRepositoryMockRecorder) Count(ctx, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockIUserRepository)(nil).Count), ctx, keyword)
}

// CountSearch mocks base method.
func (m *MockIUserRepository) CountSearch(ctx context.Context, keyword string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSearch", ctx, keyword)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSearch indicates an expected call of CountSearch.
func (mr *MockIUserRepositoryMockRecorder) CountSearch(ctx, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSearch", reflect.TypeOf((*MockIUserRepository)(nil).CountSearch), ctx, keyword)
}

// Create mocks base method.
func (m *MockIUserRepository) Create(ctx context.Context, u domain.User) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, u)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIUserRepositoryMockRecorder) Create(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIUserRepository)(nil).Create), ctx, u)
}

// Delete mocks base method.
func (m *MockIUserRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIUserRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIUserRepository)(nil).Delete), ctx, id)
}

// DeleteIdentity mocks base method.
func (m *MockIUserRepository) DeleteIdentity(ctx context.Context, uid int64, provider, identityID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIdentity", ctx, uid, provider, identityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIdentity indicates an expected call of DeleteIdentity.
func (mr *MockIUserRepositoryMockRecorder) DeleteIdentity(ctx, uid, provider, identityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIdentity", reflect.TypeOf((*MockIUserRepository)(nil).DeleteIdentity), ctx, uid, provider, identityID)
}

// DeleteMfaToken mocks base method.
func (m *MockIUserRepository) DeleteMfaToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMfaToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMfaToken indicates an expected call of DeleteMfaToken.
func (mr *MockIUserRepositoryMockRecorder) DeleteMfaToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMfaToken", reflect.TypeOf((*MockIUserRepository)(nil).DeleteMfaToken), ctx, token)
}

// FindByEmail mocks base method.
func (m *MockIUserRepository) FindByEmail(ctx context.Context, email string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockIUserRepositoryMockRecorder) FindByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockIUserRepository)(nil).FindByEmail), ctx, email)
}

// FindById mocks base method.
func (m *MockIUserRepository) FindById(ctx context.Context, id int64) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockIUserRepositoryMockRecorder) FindById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockIUserRepository)(nil).FindById), ctx, id)
}

// FindByIdentity mocks base method.
func (m *MockIUserRepository) FindByIdentity(ctx context.Context, provider, identityID string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIdentity", ctx, provider, identityID)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIdentity indicates an expected call of FindByIdentity.
func (mr *MockIUserRepositoryMockRecorder) FindByIdentity(ctx, provider, identityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIdentity", reflect.TypeOf((*MockIUserRepository)(nil).FindByIdentity), ctx, provider, identityID)
}

// FindByIds mocks base method.
func (m *MockIUserRepository) FindByIds(ctx context.Context, ids []int64) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIds", ctx, ids)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIds indicates an expected call of FindByIds.
func (mr *MockIUserRepositoryMockRecorder) FindByIds(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIds", reflect.TypeOf((*MockIUserRepository)(nil).FindByIds), ctx, ids)
}

// FindByUsername mocks base method.
func (m *MockIUserRepository) FindByUsername(ctx context.Context, username string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUsername", ctx, username)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUsername indicates an expected call of FindByUsername.
func (mr *MockIUserRepositoryMockRecorder) FindByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUsername", reflect.TypeOf((*MockIUserRepository)(nil).FindByUsername), ctx, username)
}

// FindByUsernames mocks base method.
func (m *MockIUserRepository) FindByUsernames(ctx context.Context, usernames []string) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUsernames", ctx, usernames)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUsernames indicates an expected call of FindByUsernames.
func (mr *MockIUserRepositoryMockRecorder) FindByUsernames(ctx, usernames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUsernames", reflect.TypeOf((*MockIUserRepository)(nil).FindByUsernames), ctx, usernames)
}

// FindIdentitiesByUserID mocks base method.
func (m *MockIUserRepository) FindIdentitiesByUserID(ctx context.Context, userID int64, provider string) ([]domain.UserIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindIdentitiesByUserID", ctx, userID, provider)
	ret0, _ := ret[0].([]domain.UserIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindIdentitiesByUserID indicates an expected call of FindIdentitiesByUserID.
func (mr *MockIUserRepositoryMockRecorder) FindIdentitiesByUserID(ctx, userID, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindIdentitiesByUserID", reflect.TypeOf((*MockIUserRepository)(nil).FindIdentitiesByUserID), ctx, userID, provider)
}

// FindUserByIdentity mocks base method.
func (m *MockIUserRepository) FindUserByIdentity(ctx context.Context, provider, identityKey string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByIdentity", ctx, provider, identityKey)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByIdentity indicates an expected call of FindUserByIdentity.
func (mr *MockIUserRepositoryMockRecorder) FindUserByIdentity(ctx, provider, identityKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByIdentity", reflect.TypeOf((*MockIUserRepository)(nil).FindUserByIdentity), ctx, provider, identityKey)
}

// FindUsersByUsernames mocks base method.
func (m *MockIUserRepository) FindUsersByUsernames(ctx context.Context, usernames []string) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUsersByUsernames", ctx, usernames)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUsersByUsernames indicates an expected call of FindUsersByUsernames.
func (mr *MockIUserRepositoryMockRecorder) FindUsersByUsernames(ctx, usernames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUsersByUsernames", reflect.TypeOf((*MockIUserRepository)(nil).FindUsersByUsernames), ctx, usernames)
}

// GetAttachedUsersWithFilter mocks base method.
func (m *MockIUserRepository) GetAttachedUsersWithFilter(ctx context.Context, roleCode string, offset, limit int64, keyword string) ([]domain.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachedUsersWithFilter", ctx, roleCode, offset, limit, keyword)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAttachedUsersWithFilter indicates an expected call of GetAttachedUsersWithFilter.
func (mr *MockIUserRepositoryMockRecorder) GetAttachedUsersWithFilter(ctx, roleCode, offset, limit, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachedUsersWithFilter", reflect.TypeOf((*MockIUserRepository)(nil).GetAttachedUsersWithFilter), ctx, roleCode, offset, limit, keyword)
}

// GetBindState mocks base method.
func (m *MockIUserRepository) GetBindState(ctx context.Context, token string) (domain.OidcIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBindState", ctx, token)
	ret0, _ := ret[0].(domain.OidcIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBindState indicates an expected call of GetBindState.
func (mr *MockIUserRepositoryMockRecorder) GetBindState(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBindState", reflect.TypeOf((*MockIUserRepository)(nil).GetBindState), ctx, token)
}

// GetMfaToken mocks base method.
func (m *MockIUserRepository) GetMfaToken(ctx context.Context, token string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMfaToken", ctx, token)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMfaToken indicates an expected call of GetMfaToken.
func (mr *MockIUserRepositoryMockRecorder) GetMfaToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMfaToken", reflect.TypeOf((*MockIUserRepository)(nil).GetMfaToken), ctx, token)
}

// GetPasskeyState mocks base method.
func (m *MockIUserRepository) GetPasskeyState(ctx context.Context, token string) (webauthn.SessionData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPasskeyState", ctx, token)
	ret0, _ := ret[0].(webauthn.SessionData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPasskeyState indicates an expected call of GetPasskeyState.
func (mr *MockIUserRepositoryMockRecorder) GetPasskeyState(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasskeyState", reflect.TypeOf((*MockIUserRepository)(nil).GetPasskeyState), ctx, token)
}

// IncFailedAttempts mocks base method.
func (m *MockIUserRepository) IncFailedAttempts(ctx context.Context, username string, maxAttempts, lockoutMinutes int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncFailedAttempts", ctx, username, maxAttempts, lockoutMinutes)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncFailedAttempts indicates an expected call of IncFailedAttempts.
func (mr *MockIUserRepositoryMockRecorder) IncFailedAttempts(ctx, username, maxAttempts, lockoutMinutes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncFailedAttempts", reflect.TypeOf((*MockIUserRepository)(nil).IncFailedAttempts), ctx, username, maxAttempts, lockoutMinutes)
}

// IncMfaAttempts mocks base method.
func (m *MockIUserRepository) IncMfaAttempts(ctx context.Context, token string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncMfaAttempts", ctx, token)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncMfaAttempts indicates an expected call of IncMfaAttempts.
func (mr *MockIUserRepositoryMockRecorder) IncMfaAttempts(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncMfaAttempts", reflect.TypeOf((*MockIUserRepository)(nil).IncMfaAttempts), ctx, token)
}

// IsLocked mocks base method.
func (m *MockIUserRepository) IsLocked(ctx context.Context, username string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLocked", ctx, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsLocked indicates an expected call of IsLocked.
func (mr *MockIUserRepositoryMockRecorder) IsLocked(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLocked", reflect.TypeOf((*MockIUserRepository)(nil).IsLocked), ctx, username)
}

// List mocks base method.
func (m *MockIUserRepository) List(ctx context.Context, offset, limit int64, keyword string) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit, keyword)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIUserRepositoryMockRecorder) List(ctx, offset, limit, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIUserRepository)(nil).List), ctx, offset, limit, keyword)
}

// SaveIdentity mocks base method.
func (m *MockIUserRepository) SaveIdentity(ctx context.Context, ui domain.UserIdentity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveIdentity", ctx, ui)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveIdentity indicates an expected call of SaveIdentity.
func (mr *MockIUserRepositoryMockRecorder) SaveIdentity(ctx, ui any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveIdentity", reflect.TypeOf((*MockIUserRepository)(nil).SaveIdentity), ctx, ui)
}

// Search mocks base method.
func (m *MockIUserRepository) Search(ctx context.Context, keyword string, offset, limit int64) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, keyword, offset, limit)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockIUserRepositoryMockRecorder) Search(ctx, keyword, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockIUserRepository)(nil).Search), ctx, keyword, offset, limit)
}

// SetBindState mocks base method.
func (m *MockIUserRepository) SetBindState(ctx context.Context, token string, ident domain.OidcIdentity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBindState", ctx, token, ident)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBindState indicates an expected call of SetBindState.
func (mr *MockIUserRepositoryMockRecorder) SetBindState(ctx, token, ident any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBindState", reflect.TypeOf((*MockIUserRepository)(nil).SetBindState), ctx, token, ident)
}

// SetMfaToken mocks base method.
func (m *MockIUserRepository) SetMfaToken(ctx context.Context, token string, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMfaToken", ctx, token, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMfaToken indicates an expected call of SetMfaToken.
func (mr *MockIUserRepositoryMockRecorder) SetMfaToken(ctx, token, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMfaToken", reflect.TypeOf((*MockIUserRepository)(nil).SetMfaToken), ctx, token, userID)
}

// SetPasskeyState mocks base method.
func (m *MockIUserRepository) SetPasskeyState(ctx context.Context, token string, data webauthn.SessionData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPasskeyState", ctx, token, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPasskeyState indicates an expected call of SetPasskeyState.
func (mr *MockIUserRepositoryMockRecorder) SetPasskeyState(ctx, token, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPasskeyState", reflect.TypeOf((*MockIUserRepository)(nil).SetPasskeyState), ctx, token, data)
}

// Update mocks base method.
func (m *MockIUserRepository) Update(ctx context.Context, u domain.User) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, u)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIUserRepositoryMockRecorder) Update(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIUserRepository)(nil).Update), ctx, u)
}

// UpdateLastActiveTenantID mocks base method.
func (m *MockIUserRepository) UpdateLastActiveTenantID(ctx context.Context, id, tenantID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastActiveTenantID", ctx, id, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastActiveTenantID indicates an expected call of UpdateLastActiveTenantID.
func (mr *MockIUserRepositoryMockRecorder) UpdateLastActiveTenantID(ctx, id, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastActiveTenantID", reflect.TypeOf((*MockIUserRepository)(nil).UpdateLastActiveTenantID), ctx, id, tenantID)
}

// UpdateLastLoginAt mocks base method.
func (m *MockIUserRepository) UpdateLastLoginAt(ctx context.Context, id, loginAt int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLoginAt", ctx, id, loginAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLoginAt indicates an expected call of UpdateLastLoginAt.
func (mr *MockIUserRepositoryMockRecorder) UpdateLastLoginAt(ctx, id, loginAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLoginAt", reflect.TypeOf((*MockIUserRepository)(nil).UpdateLastLoginAt), ctx, id, loginAt)
}

// UpdateMfa mocks base method.
func (m *MockIUserRepository) UpdateMfa(ctx context.Context, id int64, mfaType, mfaSecret string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMfa", ctx, id, mfaType, mfaSecret)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMfa indicates an expected call of UpdateMfa.
func (mr *MockIUserRepositoryMockRecorder) UpdateMfa(ctx, id, mfaType, mfaSecret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMfa", reflect.TypeOf((*MockIUserRepository)(nil).UpdateMfa), ctx, id, mfaType, mfaSecret)
}
