// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/Havens-blog/e-iam/internal/event/audit"
	"github.com/Havens-blog/e-iam/internal/grpc"
	"github.com/Havens-blog/e-iam/internal/repository"
	"github.com/Havens-blog/e-iam/internal/repository/cache"
	"github.com/Havens-blog/e-iam/internal/repository/dao"
	audit2 "github.com/Havens-blog/e-iam/internal/service/audit"
	"github.com/Havens-blog/e-iam/internal/service/department"
	"github.com/Havens-blog/e-iam/internal/service/discovery"
	"github.com/Havens-blog/e-iam/internal/service/group"
	"github.com/Havens-blog/e-iam/internal/service/idp"
	"github.com/Havens-blog/e-iam/internal/service/idp/cas"
	"github.com/Havens-blog/e-iam/internal/service/idp/claims"
	"github.com/Havens-blog/e-iam/internal/service/idp/oidc"
	"github.com/Havens-blog/e-iam/internal/service/idp/saml"
	"github.com/Havens-blog/e-iam/internal/service/invitation"
	"github.com/Havens-blog/e-iam/internal/service/permission"
	"github.com/Havens-blog/e-iam/internal/service/permission/checker"
	"github.com/Havens-blog/e-iam/internal/service/policy"
	"github.com/Havens-blog/e-iam/internal/service/resource"
	"github.com/Havens-blog/e-iam/internal/service/resource/ingestion"
	"github.com/Havens-blog/e-iam/internal/service/role"
	"github.com/Havens-blog/e-iam/internal/service/tenant"
	"github.com/Havens-blog/e-iam/internal/service/user"
	"github.com/Havens-blog/e-iam/internal/service/user/ldap"
	"github.com/Havens-blog/e-iam/internal/service/user/passkey"
	audit3 "github.com/Havens-blog/e-iam/internal/web/audit"
	department2 "github.com/Havens-blog/e-iam/internal/web/department"
	discovery2 "github.com/Havens-blog/e-iam/internal/web/discovery"
	group2 "github.com/Havens-blog/e-iam/internal/web/group"
	"github.com/Havens-blog/e-iam/internal/web/identity_source"
	idp2 "github.com/Havens-blog/e-iam/internal/web/idp"
	invitation2 "github.com/Havens-blog/e-iam/internal/web/invitation"
	permission2 "github.com/Havens-blog/e-iam/internal/web/permission"
	policy2 "github.com/Havens-blog/e-iam/internal/web/policy"
	role2 "github.com/Havens-blog/e-iam/internal/web/role"
	tenant2 "github.com/Havens-blog/e-iam/internal/web/tenant"
	user2 "github.com/Havens-blog/e-iam/internal/web/user"
	"github.com/Havens-blog/e-iam/pkg/web/middleware"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

// InitApp 统一编排并装配完整企业级 EIAM 应用服务实例
func InitApp() (*App, error) {
	cmdable := InitRedis()
	provider := InitSession(cmdable)
	listener := InitListener()
	v := InitGinMiddlewares()
	db := InitDB()
	iUserDAO := dao.NewUserDAO(db)
	iTenantDAO := dao.NewTenantDAO(db)
	iUserCache := cache.NewUserCache(cmdable)
	iUserRepository := repository.NewUserRepository(iUserDAO, iTenantDAO, iUserCache)
	iTenantRepository := repository.NewTenantRepository(iTenantDAO)
	iRoleDAO := dao.NewRoleDAO(db)
	iRoleRepository := repository.NewRoleRepository(iRoleDAO)
	iPolicyDAO := dao.NewPolicyDAO(db)
	iPolicyRepository := repository.NewPolicyRepository(iPolicyDAO)
	iPermissionDAO := dao.NewPermissionDAO(db)
	iPermissionCache := cache.NewPermissionCache(cmdable)
	iPermissionRepository := repository.NewPermissionRepository(iPermissionDAO, iPermissionCache)
	iBoundaryChecker := checker.NewBoundaryChecker(iPermissionRepository)
	iPolicyService := policy.NewPolicyService(iPolicyRepository, iBoundaryChecker)
	syncedEnforcer := InitCasbin(db)
	iRoleService := role.NewRoleService(iRoleRepository, iPolicyService, iBoundaryChecker, syncedEnforcer)
	iTenantKeyDAO := dao.NewTenantKeyDAO(db)
	iTenantKeyRepository := repository.NewTenantKeyRepository(iTenantKeyDAO)
	iTenantKeyService := tenant.NewTenantKeyService(iTenantKeyRepository)
	iTenantService := tenant.NewTenantService(iTenantRepository, iUserRepository, iRoleService, syncedEnforcer, iTenantKeyService)
	iIdentitySourceDAO := dao.NewIdentitySourceDAO(db)
	iIdentitySourceCache := cache.NewIdentitySourceCache(cmdable)
	iIdentitySourceRepository := repository.NewIdentitySourceRepository(iIdentitySourceDAO, iIdentitySourceCache)
	cryptoManager := InitCryptoManager()
	iService := InitIdentitySourceService(iIdentitySourceRepository, cryptoManager)
	iUserService := user.NewUserService(iUserRepository, iTenantService, iService, cryptoManager)
	iAuditProducer := audit.NewProducer(cmdable)
	v2 := InitCredentialProviders(iService)
	iAuthCoordinator := user.NewAuthCoordinator(iUserRepository, iTenantService, iService, cryptoManager, iAuditProducer, v2)
	client := InitRedisSearch()
	redisearchLdapUserCache := InitLdapUserCache(client)
	iLdapService := ldap.NewLdapService(iUserRepository, iTenantService, iService, redisearchLdapUserCache)
	iPasskeyService := passkey.NewPasskeyService(iUserRepository, iService)
	iGroupDAO := dao.NewGroupDAO(db)
	iGroupRepository := repository.NewGroupRepository(iGroupDAO, iUserRepository)
	iGroupService := group.NewGroupService(iGroupRepository, iUserRepository, syncedEnforcer)
	iSubjectRegistry := InitSearchSubjectProviders(iRoleService, iUserService, iGroupService)
	iResourceDAO := dao.NewResourceDAO(db)
	iResourceCache := cache.NewResourceCache(cmdable)
	iResourceRepository := repository.NewResourceRepository(iResourceDAO, iResourceCache)
	iServiceDAO := dao.NewServiceDAO(db)
	iServiceRepository := repository.NewServiceRepository(iServiceDAO)
	iResourceService := resource.NewResourceService(iResourceRepository, iServiceRepository)
	iAuthorizer := InitOPA()
	iPermissionService := permission.NewPermissionService(syncedEnforcer, iPolicyService, iRoleService, iSubjectRegistry, iResourceService, iPermissionRepository, iAuthorizer, iBoundaryChecker, iTenantRepository)
	handler := user2.NewUserHandler(iUserService, iAuthCoordinator, iTenantService, iLdapService, iService, iPasskeyService, iPermissionService)
	policyHandler := policy2.NewHandler(iPolicyService, iUserService, iPermissionService)
	tenantHandler := tenant2.NewHandler(iTenantService, iPermissionService)
	auditConfig := InitAuditConfig()
	iAuditMatcher := InitAuditMatcher(auditConfig)
	permissionHandler := permission2.NewHandler(iPermissionService, iAuditMatcher)
	roleHandler := role2.NewHandler(iRoleService, iPermissionService, iUserService)
	iDepartmentDAO := dao.NewDepartmentDAO(db)
	iDepartmentRepository := repository.NewDepartmentRepository(iDepartmentDAO, iUserRepository)
	iDepartmentService := department.NewDepartmentService(iDepartmentRepository)
	departmentHandler := department2.NewHandler(iDepartmentService)
	groupHandler := group2.NewHandler(iGroupService, iRoleService)
	identity_sourceHandler := identity_source.NewHandler(iService)
	iInvitationDAO := dao.NewInvitationDAO(db)
	iInvitationRepository := repository.NewInvitationRepository(iInvitationDAO)
	iInvitationService := invitation.NewInvitationService(iInvitationRepository, iTenantRepository, iPermissionService, iUserService)
	invitationHandler := invitation2.NewHandler(iInvitationService, provider)
	clientv3Client := InitEtcd()
	reporter := InitCapabilityRegistry(clientv3Client)
	iDiscoveryCache := cache.NewDiscoveryCache(cmdable)
	iDiscoveryService := discovery.NewDiscoveryService(reporter, iDiscoveryCache)
	iTokenService := discovery.NewTokenService(iTenantKeyRepository, iServiceRepository)
	discoveryHandler := discovery2.NewHandler(iDiscoveryService, iTokenService)
	iAuditDAO := dao.NewAuditDAO(db)
	iAuditRepository := repository.NewAuditRepository(iAuditDAO)
	iAuditService := audit2.NewService(iAuditRepository)
	auditHandler := audit3.NewHandler(iAuditService, iAuditProducer)
	iApplicationDAO := dao.NewApplicationDAO(db)
	iOidcCache := cache.NewOidcCache(cmdable)
	iApplicationRepository := repository.NewApplicationRepository(iApplicationDAO, iOidcCache)
	idpIService := idp.NewApplicationService(iApplicationRepository)
	iClaimsResolver := claims.NewClaimsResolver(iUserRepository, iPermissionService)
	idPConfig := InitIdPConfig()
	iKeyManager, err := InitKeyManager(idPConfig, iOidcCache)
	if err != nil {
		return nil, err
	}
	iOidcService := oidc.NewService(iApplicationRepository, iClaimsResolver, iTenantService, iOidcCache, iKeyManager, iAuditProducer)
	iCasCache := cache.NewCasCache(cmdable)
	iCasService := cas.NewCasService(iCasCache, iClaimsResolver, iApplicationRepository, iTenantService)
	iSamlCache := cache.NewSamlCache(cmdable)
	iCertificateManager, err := InitSamlCertManager(idPConfig, iSamlCache)
	if err != nil {
		return nil, err
	}
	iSamlService := saml.NewSamlService(iCertificateManager, iClaimsResolver, iApplicationRepository)
	idpHandler := idp2.NewHandler(idpIService, iOidcService, iCasService, iSamlService)
	tenancyBuilder := middleware.NewTenancyBuilder(provider)
	component := InitGinWebServer(provider, listener, v, handler, policyHandler, tenantHandler, permissionHandler, roleHandler, departmentHandler, groupHandler, identity_sourceHandler, invitationHandler, discoveryHandler, auditHandler, idpHandler, tenancyBuilder, iPermissionService, iAuditProducer)
	userServiceServer := grpc.NewUserServer(iUserService, iPermissionService)
	tenantServiceServer := grpc.NewTenantServiceServer(iTenantKeyService)
	departmentServiceServer := grpc.NewDepartmentServer(iDepartmentService)
	server := InitGrpcServer(userServiceServer, tenantServiceServer, departmentServiceServer)
	engine := ingestion.NewEngine(iPermissionRepository, iResourceRepository, iServiceRepository)
	iInitializer := resource.NewResourceInitializer(engine, reporter)
	v3 := InitProviders()
	dlockClient := InitDLock(cmdable)
	worker := discovery.NewWorker(clientv3Client, iDiscoveryService, iInitializer, dlockClient)
	consumer := audit.NewConsumer(cmdable, iAuditRepository)
	v4 := InitTasks(worker, consumer)
	app := &App{
		Web:       component,
		Server:    server,
		Init:      iInitializer,
		Providers: v3,
		Tasks:     v4,
	}
	return app, nil
}

// InitTokenService 为 CLI Token 生成命令提供专用的轻量级依赖注入树 (Wire 原生自动编排，仅需 DB 依赖)
func InitTokenService() (discovery.ITokenService, error) {
	db := InitDBWithoutMigrate()
	iTenantKeyDAO := dao.NewTenantKeyDAO(db)
	iTenantKeyRepository := repository.NewTenantKeyRepository(iTenantKeyDAO)
	iServiceDAO := dao.NewServiceDAO(db)
	iServiceRepository := repository.NewServiceRepository(iServiceDAO)
	iTokenService := discovery.NewTokenService(iTenantKeyRepository, iServiceRepository)
	return iTokenService, nil
}
