// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/Duke1616/eiam/internal/grpc"
	"github.com/Duke1616/eiam/internal/repository"
	"github.com/Duke1616/eiam/internal/repository/cache"
	"github.com/Duke1616/eiam/internal/repository/dao"
	"github.com/Duke1616/eiam/internal/service/department"
	discovery2 "github.com/Duke1616/eiam/internal/service/discovery"
	"github.com/Duke1616/eiam/internal/service/group"
	"github.com/Duke1616/eiam/internal/service/invitation"
	"github.com/Duke1616/eiam/internal/service/permission"
	"github.com/Duke1616/eiam/internal/service/permission/checker"
	"github.com/Duke1616/eiam/internal/service/policy"
	"github.com/Duke1616/eiam/internal/service/resource"
	"github.com/Duke1616/eiam/internal/service/resource/ingestion"
	"github.com/Duke1616/eiam/internal/service/role"
	"github.com/Duke1616/eiam/internal/service/tenant"
	"github.com/Duke1616/eiam/internal/service/user"
	"github.com/Duke1616/eiam/internal/service/user/ldap"
	"github.com/Duke1616/eiam/internal/service/user/passkey"
	department2 "github.com/Duke1616/eiam/internal/web/department"
	"github.com/Duke1616/eiam/internal/web/discovery"
	group2 "github.com/Duke1616/eiam/internal/web/group"
	"github.com/Duke1616/eiam/internal/web/identity_source"
	invitation2 "github.com/Duke1616/eiam/internal/web/invitation"
	permission2 "github.com/Duke1616/eiam/internal/web/permission"
	policy2 "github.com/Duke1616/eiam/internal/web/policy"
	role2 "github.com/Duke1616/eiam/internal/web/role"
	tenant2 "github.com/Duke1616/eiam/internal/web/tenant"
	user2 "github.com/Duke1616/eiam/internal/web/user"
	"github.com/Duke1616/eiam/pkg/web/middleware"
	"github.com/RediSearch/redisearch-go/v2/redisearch"
	"github.com/google/wire"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	cmdable := InitRedis()
	provider := InitSession(cmdable)
	listener := InitListener()
	v := InitGinMiddlewares()
	db := InitDB()
	iUserDAO := dao.NewUserDAO(db)
	iTenantDAO := dao.NewTenantDAO(db)
	iUserCache := cache.NewUserCache(cmdable)
	iUserRepository := repository.NewUserRepository(iUserDAO, iTenantDAO, iUserCache)
	iTenantRepository := repository.NewTenantRepository(iTenantDAO)
	iRoleDAO := dao.NewRoleDAO(db)
	iRoleRepository := repository.NewRoleRepository(iRoleDAO)
	iPolicyDAO := dao.NewPolicyDAO(db)
	iPolicyRepository := repository.NewPolicyRepository(iPolicyDAO)
	iPermissionDAO := dao.NewPermissionDAO(db)
	iPermissionRepository := repository.NewPermissionRepository(iPermissionDAO)
	iBoundaryChecker := checker.NewBoundaryChecker(iPermissionRepository)
	iPolicyService := policy.NewPolicyService(iPolicyRepository, iBoundaryChecker)
	syncedEnforcer := InitCasbin(db)
	iRoleService := role.NewRoleService(iRoleRepository, iPolicyService, iBoundaryChecker, syncedEnforcer)
	iTenantKeyDAO := dao.NewTenantKeyDAO(db)
	iTenantKeyRepository := repository.NewTenantKeyRepository(iTenantKeyDAO)
	iTenantKeyService := tenant.NewTenantKeyService(iTenantKeyRepository)
	iTenantService := tenant.NewTenantService(iTenantRepository, iUserRepository, iRoleService, syncedEnforcer, iTenantKeyService)
	iIdentitySourceDAO := dao.NewIdentitySourceDAO(db)
	iIdentitySourceCache := cache.NewIdentitySourceCache(cmdable)
	iIdentitySourceRepository := repository.NewIdentitySourceRepository(iIdentitySourceDAO, iIdentitySourceCache)
	cryptoManager := InitCryptoManager()
	iService := InitIdentitySourceService(iIdentitySourceRepository, cryptoManager)
	v2 := InitCredentialProviders(iService)
	iUserService := user.NewUserService(iUserRepository, iTenantService, iService, v2, cryptoManager)
	client := InitRedisSearch()
	redisearchLdapUserCache := InitLdapUserCache(client)
	ldapService := ldap.NewLdapService(iUserRepository, iTenantService, iService, redisearchLdapUserCache)
	iPasskeyService := passkey.NewPasskeyService(iUserRepository, iService)
	iGroupDAO := dao.NewGroupDAO(db)
	iGroupRepository := repository.NewGroupRepository(iGroupDAO, iUserRepository)
	iGroupService := group.NewGroupService(iGroupRepository, iUserRepository, syncedEnforcer)
	iSubjectRegistry := InitSearchSubjectProviders(iRoleService, iUserService, iGroupService)
	iResourceDAO := dao.NewResourceDAO(db)
	iResourceRepository := repository.NewResourceRepository(iResourceDAO)
	iServiceDAO := dao.NewServiceDAO(db)
	iServiceRepository := repository.NewServiceRepository(iServiceDAO)
	iResourceService := resource.NewResourceService(iResourceRepository, iServiceRepository)
	iAuthorizer := InitOPA()
	iPermissionService := permission.NewPermissionService(syncedEnforcer, iPolicyService, iRoleService, iSubjectRegistry, iResourceService, iPermissionRepository, iAuthorizer, iBoundaryChecker, iTenantRepository)
	handler := user2.NewUserHandler(iUserService, iTenantService, ldapService, iService, iPasskeyService, iPermissionService, provider)
	policyHandler := policy2.NewHandler(iPolicyService, iUserService, iPermissionService)
	tenantHandler := tenant2.NewHandler(iTenantService, iPermissionService, provider)
	permissionHandler := permission2.NewHandler(iPermissionService, provider)
	roleHandler := role2.NewHandler(iRoleService, iPermissionService, iUserService)
	iDepartmentDAO := dao.NewDepartmentDAO(db)
	iDepartmentRepository := repository.NewDepartmentRepository(iDepartmentDAO, iUserRepository)
	iDepartmentService := department.NewDepartmentService(iDepartmentRepository)
	departmentHandler := department2.NewHandler(iDepartmentService)
	groupHandler := group2.NewHandler(iGroupService, iRoleService)
	identity_sourceHandler := identity_source.NewHandler(iService)
	iInvitationDAO := dao.NewInvitationDAO(db)
	iInvitationRepository := repository.NewInvitationRepository(iInvitationDAO)
	iInvitationService := invitation.NewInvitationService(iInvitationRepository, iTenantRepository, iPermissionService, iUserService)
	invitationHandler := invitation2.NewHandler(iInvitationService, provider)
	clientv3Client := InitEtcd()
	registry := InitCapabilityRegistry(clientv3Client)
	discoveryHandler := discovery.NewHandler(registry)
	tenancyBuilder := middleware.NewTenancyBuilder(provider)
	component := InitGinWebServer(provider, listener, v, handler, policyHandler, tenantHandler, permissionHandler, roleHandler, departmentHandler, groupHandler, identity_sourceHandler, invitationHandler, discoveryHandler, tenancyBuilder, iPermissionService)
	userServiceServer := grpc.NewUserServer(iUserService, iPermissionService)
	tenantServiceServer := grpc.NewTenantServiceServer(iTenantKeyService)
	departmentServiceServer := grpc.NewDepartmentServer(iDepartmentService)
	server := InitGrpcServer(userServiceServer, tenantServiceServer, departmentServiceServer)
	engine := ingestion.NewEngine(iPermissionRepository, iResourceRepository, iServiceRepository)
	iInitializer := resource.NewResourceInitializer(engine, registry)
	v3 := InitProviders()
	dlockClient := InitDLock(cmdable)
	worker := discovery2.NewWorker(clientv3Client, engine, iInitializer, dlockClient)
	v4 := InitTasks(worker)
	app := &App{
		Web:       component,
		Server:    server,
		Init:      iInitializer,
		Providers: v3,
		Tasks:     v4,
	}
	return app, nil
}

// wire.go:

var BaseSet = wire.NewSet(
	InitDB,
	InitRedis,
	InitSession,
	InitCasbin,
	InitListener,
	InitOPA,
	InitEtcd,
	InitDLock,
	InitCapabilityRegistry,

	InitRedisSearch,
	InitCredentialProviders,

	InitServiceConfig,
	InitCryptoManager,
)

func InitLdapUserCache(conn *redisearch.Client) cache.RedisearchLdapUserCache {
	return cache.NewRedisearchLdapUserCache(conn)
}
