// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Duke1616/eiam/internal/repository/dao (interfaces: IAuditDAO)
//
// Generated by this command:
//
//	mockgen -package=daomocks -destination=./mocks/audit.mock.go github.com/Duke1616/eiam/internal/repository/dao IAuditDAO
//

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eiam/internal/domain"
	dao "github.com/Duke1616/eiam/internal/repository/dao"
	gomock "go.uber.org/mock/gomock"
)

// MockIAuditDAO is a mock of IAuditDAO interface.
type MockIAuditDAO struct {
	ctrl     *gomock.Controller
	recorder *MockIAuditDAOMockRecorder
	isgomock struct{}
}

// MockIAuditDAOMockRecorder is the mock recorder for MockIAuditDAO.
type MockIAuditDAOMockRecorder struct {
	mock *MockIAuditDAO
}

// NewMockIAuditDAO creates a new mock instance.
func NewMockIAuditDAO(ctrl *gomock.Controller) *MockIAuditDAO {
	mock := &MockIAuditDAO{ctrl: ctrl}
	mock.recorder = &MockIAuditDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuditDAO) EXPECT() *MockIAuditDAOMockRecorder {
	return m.recorder
}

// BatchInsertAuthLogs mocks base method.
func (m *MockIAuditDAO) BatchInsertAuthLogs(ctx context.Context, logs []dao.AuditAuthLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchInsertAuthLogs", ctx, logs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchInsertAuthLogs indicates an expected call of BatchInsertAuthLogs.
func (mr *MockIAuditDAOMockRecorder) BatchInsertAuthLogs(ctx, logs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsertAuthLogs", reflect.TypeOf((*MockIAuditDAO)(nil).BatchInsertAuthLogs), ctx, logs)
}

// BatchInsertOperationLogs mocks base method.
func (m *MockIAuditDAO) BatchInsertOperationLogs(ctx context.Context, logs []dao.AuditOperationLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchInsertOperationLogs", ctx, logs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchInsertOperationLogs indicates an expected call of BatchInsertOperationLogs.
func (mr *MockIAuditDAOMockRecorder) BatchInsertOperationLogs(ctx, logs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsertOperationLogs", reflect.TypeOf((*MockIAuditDAO)(nil).BatchInsertOperationLogs), ctx, logs)
}

// ListAuthLogs mocks base method.
func (m *MockIAuditDAO) ListAuthLogs(ctx context.Context, filter domain.AuthLogFilter, offset, limit int) ([]dao.AuditAuthLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuthLogs", ctx, filter, offset, limit)
	ret0, _ := ret[0].([]dao.AuditAuthLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAuthLogs indicates an expected call of ListAuthLogs.
func (mr *MockIAuditDAOMockRecorder) ListAuthLogs(ctx, filter, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuthLogs", reflect.TypeOf((*MockIAuditDAO)(nil).ListAuthLogs), ctx, filter, offset, limit)
}

// ListOperationLogs mocks base method.
func (m *MockIAuditDAO) ListOperationLogs(ctx context.Context, filter domain.OperationLogFilter, offset, limit int) ([]dao.AuditOperationLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOperationLogs", ctx, filter, offset, limit)
	ret0, _ := ret[0].([]dao.AuditOperationLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListOperationLogs indicates an expected call of ListOperationLogs.
func (mr *MockIAuditDAOMockRecorder) ListOperationLogs(ctx, filter, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOperationLogs", reflect.TypeOf((*MockIAuditDAO)(nil).ListOperationLogs), ctx, filter, offset, limit)
}
