// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Duke1616/eiam/internal/repository/dao (interfaces: IPermissionDAO)
//
// Generated by this command:
//
//	mockgen -package=daomocks -destination=./mocks/permission.mock.go github.com/Duke1616/eiam/internal/repository/dao IPermissionDAO
//

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"

	dao "github.com/Duke1616/eiam/internal/repository/dao"
	gomock "go.uber.org/mock/gomock"
)

// MockIPermissionDAO is a mock of IPermissionDAO interface.
type MockIPermissionDAO struct {
	ctrl     *gomock.Controller
	recorder *MockIPermissionDAOMockRecorder
	isgomock struct{}
}

// MockIPermissionDAOMockRecorder is the mock recorder for MockIPermissionDAO.
type MockIPermissionDAOMockRecorder struct {
	mock *MockIPermissionDAO
}

// NewMockIPermissionDAO creates a new mock instance.
func NewMockIPermissionDAO(ctrl *gomock.Controller) *MockIPermissionDAO {
	mock := &MockIPermissionDAO{ctrl: ctrl}
	mock.recorder = &MockIPermissionDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPermissionDAO) EXPECT() *MockIPermissionDAOMockRecorder {
	return m.recorder
}

// BatchInsert mocks base method.
func (m *MockIPermissionDAO) BatchInsert(ctx context.Context, perms []dao.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchInsert", ctx, perms)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchInsert indicates an expected call of BatchInsert.
func (mr *MockIPermissionDAOMockRecorder) BatchInsert(ctx, perms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsert", reflect.TypeOf((*MockIPermissionDAO)(nil).BatchInsert), ctx, perms)
}

// BindResources mocks base method.
func (m *MockIPermissionDAO) BindResources(ctx context.Context, bindings []dao.PermissionBinding) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindResources", ctx, bindings)
	ret0, _ := ret[0].(error)
	return ret0
}

// BindResources indicates an expected call of BindResources.
func (mr *MockIPermissionDAOMockRecorder) BindResources(ctx, bindings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindResources", reflect.TypeOf((*MockIPermissionDAO)(nil).BindResources), ctx, bindings)
}

// CountByService mocks base method.
func (m *MockIPermissionDAO) CountByService(ctx context.Context) ([]dao.ServiceCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByService", ctx)
	ret0, _ := ret[0].([]dao.ServiceCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByService indicates an expected call of CountByService.
func (mr *MockIPermissionDAOMockRecorder) CountByService(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByService", reflect.TypeOf((*MockIPermissionDAO)(nil).CountByService), ctx)
}

// Delete mocks base method.
func (m *MockIPermissionDAO) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIPermissionDAOMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIPermissionDAO)(nil).Delete), ctx, id)
}

// DeleteBindingsByPermCodes mocks base method.
func (m *MockIPermissionDAO) DeleteBindingsByPermCodes(ctx context.Context, codes []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBindingsByPermCodes", ctx, codes)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBindingsByPermCodes indicates an expected call of DeleteBindingsByPermCodes.
func (mr *MockIPermissionDAOMockRecorder) DeleteBindingsByPermCodes(ctx, codes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBindingsByPermCodes", reflect.TypeOf((*MockIPermissionDAO)(nil).DeleteBindingsByPermCodes), ctx, codes)
}

// DeletePermissionsByServiceAndCodes mocks base method.
func (m *MockIPermissionDAO) DeletePermissionsByServiceAndCodes(ctx context.Context, service, source string, codes []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePermissionsByServiceAndCodes", ctx, service, source, codes)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePermissionsByServiceAndCodes indicates an expected call of DeletePermissionsByServiceAndCodes.
func (mr *MockIPermissionDAOMockRecorder) DeletePermissionsByServiceAndCodes(ctx, service, source, codes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePermissionsByServiceAndCodes", reflect.TypeOf((*MockIPermissionDAO)(nil).DeletePermissionsByServiceAndCodes), ctx, service, source, codes)
}

// FindByActions mocks base method.
func (m *MockIPermissionDAO) FindByActions(ctx context.Context, actions []string) ([]dao.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByActions", ctx, actions)
	ret0, _ := ret[0].([]dao.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByActions indicates an expected call of FindByActions.
func (mr *MockIPermissionDAOMockRecorder) FindByActions(ctx, actions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByActions", reflect.TypeOf((*MockIPermissionDAO)(nil).FindByActions), ctx, actions)
}

// FindParentsByNeeds mocks base method.
func (m *MockIPermissionDAO) FindParentsByNeeds(ctx context.Context, codes []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindParentsByNeeds", ctx, codes)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindParentsByNeeds indicates an expected call of FindParentsByNeeds.
func (mr *MockIPermissionDAOMockRecorder) FindParentsByNeeds(ctx, codes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindParentsByNeeds", reflect.TypeOf((*MockIPermissionDAO)(nil).FindParentsByNeeds), ctx, codes)
}

// GetBindingsByRes mocks base method.
func (m *MockIPermissionDAO) GetBindingsByRes(ctx context.Context, resURN string) ([]dao.PermissionBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBindingsByRes", ctx, resURN)
	ret0, _ := ret[0].([]dao.PermissionBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBindingsByRes indicates an expected call of GetBindingsByRes.
func (mr *MockIPermissionDAOMockRecorder) GetBindingsByRes(ctx, resURN any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBindingsByRes", reflect.TypeOf((*MockIPermissionDAO)(nil).GetBindingsByRes), ctx, resURN)
}

// GetByCode mocks base method.
func (m *MockIPermissionDAO) GetByCode(ctx context.Context, code string) (dao.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(dao.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockIPermissionDAOMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockIPermissionDAO)(nil).GetByCode), ctx, code)
}

// Insert mocks base method.
func (m *MockIPermissionDAO) Insert(ctx context.Context, p dao.Permission) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, p)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockIPermissionDAOMockRecorder) Insert(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIPermissionDAO)(nil).Insert), ctx, p)
}

// ListAll mocks base method.
func (m *MockIPermissionDAO) ListAll(ctx context.Context) ([]dao.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]dao.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockIPermissionDAOMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockIPermissionDAO)(nil).ListAll), ctx)
}

// ListBindingsByPerm mocks base method.
func (m *MockIPermissionDAO) ListBindingsByPerm(ctx context.Context, permId int64) ([]dao.PermissionBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBindingsByPerm", ctx, permId)
	ret0, _ := ret[0].([]dao.PermissionBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBindingsByPerm indicates an expected call of ListBindingsByPerm.
func (mr *MockIPermissionDAOMockRecorder) ListBindingsByPerm(ctx, permId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBindingsByPerm", reflect.TypeOf((*MockIPermissionDAO)(nil).ListBindingsByPerm), ctx, permId)
}

// ListBindingsByResURNs mocks base method.
func (m *MockIPermissionDAO) ListBindingsByResURNs(ctx context.Context, resURNs []string) ([]dao.PermissionBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBindingsByResURNs", ctx, resURNs)
	ret0, _ := ret[0].([]dao.PermissionBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBindingsByResURNs indicates an expected call of ListBindingsByResURNs.
func (mr *MockIPermissionDAOMockRecorder) ListBindingsByResURNs(ctx, resURNs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBindingsByResURNs", reflect.TypeOf((*MockIPermissionDAO)(nil).ListBindingsByResURNs), ctx, resURNs)
}

// ListCasbinRules mocks base method.
func (m *MockIPermissionDAO) ListCasbinRules(ctx context.Context, tid, offset, limit int64, v0Prefix, v1Prefix, keyword string) ([]dao.CasbinRule, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCasbinRules", ctx, tid, offset, limit, v0Prefix, v1Prefix, keyword)
	ret0, _ := ret[0].([]dao.CasbinRule)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCasbinRules indicates an expected call of ListCasbinRules.
func (mr *MockIPermissionDAOMockRecorder) ListCasbinRules(ctx, tid, offset, limit, v0Prefix, v1Prefix, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCasbinRules", reflect.TypeOf((*MockIPermissionDAO)(nil).ListCasbinRules), ctx, tid, offset, limit, v0Prefix, v1Prefix, keyword)
}

// ListMenuBindings mocks base method.
func (m *MockIPermissionDAO) ListMenuBindings(ctx context.Context) ([]dao.PermissionBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMenuBindings", ctx)
	ret0, _ := ret[0].([]dao.PermissionBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMenuBindings indicates an expected call of ListMenuBindings.
func (mr *MockIPermissionDAOMockRecorder) ListMenuBindings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMenuBindings", reflect.TypeOf((*MockIPermissionDAO)(nil).ListMenuBindings), ctx)
}

// MarkPermissionsAsOrphan mocks base method.
func (m *MockIPermissionDAO) MarkPermissionsAsOrphan(ctx context.Context, service, source string, codes []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPermissionsAsOrphan", ctx, service, source, codes)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPermissionsAsOrphan indicates an expected call of MarkPermissionsAsOrphan.
func (mr *MockIPermissionDAOMockRecorder) MarkPermissionsAsOrphan(ctx, service, source, codes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPermissionsAsOrphan", reflect.TypeOf((*MockIPermissionDAO)(nil).MarkPermissionsAsOrphan), ctx, service, source, codes)
}

// SyncResourceBindings mocks base method.
func (m *MockIPermissionDAO) SyncResourceBindings(ctx context.Context, resURNs []string, bindings []dao.PermissionBinding) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncResourceBindings", ctx, resURNs, bindings)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncResourceBindings indicates an expected call of SyncResourceBindings.
func (mr *MockIPermissionDAOMockRecorder) SyncResourceBindings(ctx, resURNs, bindings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncResourceBindings", reflect.TypeOf((*MockIPermissionDAO)(nil).SyncResourceBindings), ctx, resURNs, bindings)
}

// Transaction mocks base method.
func (m *MockIPermissionDAO) Transaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockIPermissionDAOMockRecorder) Transaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockIPermissionDAO)(nil).Transaction), ctx, fn)
}
