// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Duke1616/eiam/internal/repository/dao (interfaces: IResourceDAO)
//
// Generated by this command:
//
//	mockgen -package=daomocks -destination=./mocks/resource.mock.go github.com/Duke1616/eiam/internal/repository/dao IResourceDAO
//

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"

	dao "github.com/Duke1616/eiam/internal/repository/dao"
	gomock "go.uber.org/mock/gomock"
)

// MockIResourceDAO is a mock of IResourceDAO interface.
type MockIResourceDAO struct {
	ctrl     *gomock.Controller
	recorder *MockIResourceDAOMockRecorder
	isgomock struct{}
}

// MockIResourceDAOMockRecorder is the mock recorder for MockIResourceDAO.
type MockIResourceDAOMockRecorder struct {
	mock *MockIResourceDAO
}

// NewMockIResourceDAO creates a new mock instance.
func NewMockIResourceDAO(ctrl *gomock.Controller) *MockIResourceDAO {
	mock := &MockIResourceDAO{ctrl: ctrl}
	mock.recorder = &MockIResourceDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIResourceDAO) EXPECT() *MockIResourceDAOMockRecorder {
	return m.recorder
}

// BatchInsertAPI mocks base method.
func (m *MockIResourceDAO) BatchInsertAPI(ctx context.Context, apis []dao.API) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchInsertAPI", ctx, apis)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchInsertAPI indicates an expected call of BatchInsertAPI.
func (mr *MockIResourceDAOMockRecorder) BatchInsertAPI(ctx, apis any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsertAPI", reflect.TypeOf((*MockIResourceDAO)(nil).BatchInsertAPI), ctx, apis)
}

// BatchUpdateMenuSort mocks base method.
func (m *MockIResourceDAO) BatchUpdateMenuSort(ctx context.Context, menus []dao.Menu) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdateMenuSort", ctx, menus)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdateMenuSort indicates an expected call of BatchUpdateMenuSort.
func (mr *MockIResourceDAOMockRecorder) BatchUpdateMenuSort(ctx, menus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdateMenuSort", reflect.TypeOf((*MockIResourceDAO)(nil).BatchUpdateMenuSort), ctx, menus)
}

// BatchUpsertMenus mocks base method.
func (m *MockIResourceDAO) BatchUpsertMenus(ctx context.Context, menus []dao.Menu) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpsertMenus", ctx, menus)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpsertMenus indicates an expected call of BatchUpsertMenus.
func (mr *MockIResourceDAOMockRecorder) BatchUpsertMenus(ctx, menus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpsertMenus", reflect.TypeOf((*MockIResourceDAO)(nil).BatchUpsertMenus), ctx, menus)
}

// DeleteAPIsByServiceAndURNs mocks base method.
func (m *MockIResourceDAO) DeleteAPIsByServiceAndURNs(ctx context.Context, service, source string, urns []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAPIsByServiceAndURNs", ctx, service, source, urns)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAPIsByServiceAndURNs indicates an expected call of DeleteAPIsByServiceAndURNs.
func (mr *MockIResourceDAOMockRecorder) DeleteAPIsByServiceAndURNs(ctx, service, source, urns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAPIsByServiceAndURNs", reflect.TypeOf((*MockIResourceDAO)(nil).DeleteAPIsByServiceAndURNs), ctx, service, source, urns)
}

// FindAPIByPath mocks base method.
func (m *MockIResourceDAO) FindAPIByPath(ctx context.Context, service, method, path string) (dao.API, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAPIByPath", ctx, service, method, path)
	ret0, _ := ret[0].(dao.API)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAPIByPath indicates an expected call of FindAPIByPath.
func (mr *MockIResourceDAOMockRecorder) FindAPIByPath(ctx, service, method, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAPIByPath", reflect.TypeOf((*MockIResourceDAO)(nil).FindAPIByPath), ctx, service, method, path)
}

// FindMenuByName mocks base method.
func (m *MockIResourceDAO) FindMenuByName(ctx context.Context, name string) (dao.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMenuByName", ctx, name)
	ret0, _ := ret[0].(dao.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMenuByName indicates an expected call of FindMenuByName.
func (mr *MockIResourceDAOMockRecorder) FindMenuByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMenuByName", reflect.TypeOf((*MockIResourceDAO)(nil).FindMenuByName), ctx, name)
}

// InsertAPI mocks base method.
func (m *MockIResourceDAO) InsertAPI(ctx context.Context, a dao.API) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAPI", ctx, a)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertAPI indicates an expected call of InsertAPI.
func (mr *MockIResourceDAOMockRecorder) InsertAPI(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAPI", reflect.TypeOf((*MockIResourceDAO)(nil).InsertAPI), ctx, a)
}

// InsertMenu mocks base method.
func (m_2 *MockIResourceDAO) InsertMenu(ctx context.Context, m dao.Menu) (int64, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "InsertMenu", ctx, m)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertMenu indicates an expected call of InsertMenu.
func (mr *MockIResourceDAOMockRecorder) InsertMenu(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMenu", reflect.TypeOf((*MockIResourceDAO)(nil).InsertMenu), ctx, m)
}

// ListAPIsByService mocks base method.
func (m *MockIResourceDAO) ListAPIsByService(ctx context.Context, service string) ([]dao.API, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAPIsByService", ctx, service)
	ret0, _ := ret[0].([]dao.API)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAPIsByService indicates an expected call of ListAPIsByService.
func (mr *MockIResourceDAOMockRecorder) ListAPIsByService(ctx, service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAPIsByService", reflect.TypeOf((*MockIResourceDAO)(nil).ListAPIsByService), ctx, service)
}

// ListAllAPIs mocks base method.
func (m *MockIResourceDAO) ListAllAPIs(ctx context.Context) ([]dao.API, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllAPIs", ctx)
	ret0, _ := ret[0].([]dao.API)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllAPIs indicates an expected call of ListAllAPIs.
func (mr *MockIResourceDAOMockRecorder) ListAllAPIs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllAPIs", reflect.TypeOf((*MockIResourceDAO)(nil).ListAllAPIs), ctx)
}

// ListAllMenus mocks base method.
func (m *MockIResourceDAO) ListAllMenus(ctx context.Context) ([]dao.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllMenus", ctx)
	ret0, _ := ret[0].([]dao.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllMenus indicates an expected call of ListAllMenus.
func (mr *MockIResourceDAOMockRecorder) ListAllMenus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllMenus", reflect.TypeOf((*MockIResourceDAO)(nil).ListAllMenus), ctx)
}

// ListMenusByNames mocks base method.
func (m *MockIResourceDAO) ListMenusByNames(ctx context.Context, names []string) ([]dao.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMenusByNames", ctx, names)
	ret0, _ := ret[0].([]dao.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMenusByNames indicates an expected call of ListMenusByNames.
func (mr *MockIResourceDAOMockRecorder) ListMenusByNames(ctx, names any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMenusByNames", reflect.TypeOf((*MockIResourceDAO)(nil).ListMenusByNames), ctx, names)
}

// ListMenusByParentID mocks base method.
func (m *MockIResourceDAO) ListMenusByParentID(ctx context.Context, parentID int64) ([]dao.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMenusByParentID", ctx, parentID)
	ret0, _ := ret[0].([]dao.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMenusByParentID indicates an expected call of ListMenusByParentID.
func (mr *MockIResourceDAOMockRecorder) ListMenusByParentID(ctx, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMenusByParentID", reflect.TypeOf((*MockIResourceDAO)(nil).ListMenusByParentID), ctx, parentID)
}

// MarkAPIsAsOrphan mocks base method.
func (m *MockIResourceDAO) MarkAPIsAsOrphan(ctx context.Context, service, source string, urns []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAPIsAsOrphan", ctx, service, source, urns)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAPIsAsOrphan indicates an expected call of MarkAPIsAsOrphan.
func (mr *MockIResourceDAOMockRecorder) MarkAPIsAsOrphan(ctx, service, source, urns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAPIsAsOrphan", reflect.TypeOf((*MockIResourceDAO)(nil).MarkAPIsAsOrphan), ctx, service, source, urns)
}

// MarkMenusAsOrphan mocks base method.
func (m *MockIResourceDAO) MarkMenusAsOrphan(ctx context.Context, names []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkMenusAsOrphan", ctx, names)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkMenusAsOrphan indicates an expected call of MarkMenusAsOrphan.
func (mr *MockIResourceDAOMockRecorder) MarkMenusAsOrphan(ctx, names any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkMenusAsOrphan", reflect.TypeOf((*MockIResourceDAO)(nil).MarkMenusAsOrphan), ctx, names)
}

// Transaction mocks base method.
func (m *MockIResourceDAO) Transaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockIResourceDAOMockRecorder) Transaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockIResourceDAO)(nil).Transaction), ctx, fn)
}

// UpdateMenu mocks base method.
func (m_2 *MockIResourceDAO) UpdateMenu(ctx context.Context, m dao.Menu) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpdateMenu", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMenu indicates an expected call of UpdateMenu.
func (mr *MockIResourceDAOMockRecorder) UpdateMenu(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMenu", reflect.TypeOf((*MockIResourceDAO)(nil).UpdateMenu), ctx, m)
}

// UpdateMenuSort mocks base method.
func (m *MockIResourceDAO) UpdateMenuSort(ctx context.Context, id, parentID, sort int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMenuSort", ctx, id, parentID, sort)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMenuSort indicates an expected call of UpdateMenuSort.
func (mr *MockIResourceDAOMockRecorder) UpdateMenuSort(ctx, id, parentID, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMenuSort", reflect.TypeOf((*MockIResourceDAO)(nil).UpdateMenuSort), ctx, id, parentID, sort)
}
