// Code generated by MockGen. DO NOT EDIT.
// Source: ./tenant.go
//
// Generated by this command:
//
//	mockgen -source=./tenant.go -package=tenantmocks -destination=./mocks/tenant.mock.go -typed ITenantService
//

// Package tenantmocks is a generated GoMock package.
package tenantmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eiam/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockITenantService is a mock of ITenantService interface.
type MockITenantService struct {
	ctrl     *gomock.Controller
	recorder *MockITenantServiceMockRecorder
	isgomock struct{}
}

// MockITenantServiceMockRecorder is the mock recorder for MockITenantService.
type MockITenantServiceMockRecorder struct {
	mock *MockITenantService
}

// NewMockITenantService creates a new mock instance.
func NewMockITenantService(ctrl *gomock.Controller) *MockITenantService {
	mock := &MockITenantService{ctrl: ctrl}
	mock.recorder = &MockITenantServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITenantService) EXPECT() *MockITenantServiceMockRecorder {
	return m.recorder
}

// AssignUser mocks base method.
func (m *MockITenantService) AssignUser(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignUser indicates an expected call of AssignUser.
func (mr *MockITenantServiceMockRecorder) AssignUser(ctx, userID any) *MockITenantServiceAssignUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignUser", reflect.TypeOf((*MockITenantService)(nil).AssignUser), ctx, userID)
	return &MockITenantServiceAssignUserCall{Call: call}
}

// MockITenantServiceAssignUserCall wrap *gomock.Call
type MockITenantServiceAssignUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceAssignUserCall) Return(arg0 error) *MockITenantServiceAssignUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceAssignUserCall) Do(f func(context.Context, int64) error) *MockITenantServiceAssignUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceAssignUserCall) DoAndReturn(f func(context.Context, int64) error) *MockITenantServiceAssignUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BatchAssignTenants mocks base method.
func (m *MockITenantService) BatchAssignTenants(ctx context.Context, userIDs, tenantIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchAssignTenants", ctx, userIDs, tenantIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchAssignTenants indicates an expected call of BatchAssignTenants.
func (mr *MockITenantServiceMockRecorder) BatchAssignTenants(ctx, userIDs, tenantIDs any) *MockITenantServiceBatchAssignTenantsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchAssignTenants", reflect.TypeOf((*MockITenantService)(nil).BatchAssignTenants), ctx, userIDs, tenantIDs)
	return &MockITenantServiceBatchAssignTenantsCall{Call: call}
}

// MockITenantServiceBatchAssignTenantsCall wrap *gomock.Call
type MockITenantServiceBatchAssignTenantsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceBatchAssignTenantsCall) Return(arg0 error) *MockITenantServiceBatchAssignTenantsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceBatchAssignTenantsCall) Do(f func(context.Context, []int64, []int64) error) *MockITenantServiceBatchAssignTenantsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceBatchAssignTenantsCall) DoAndReturn(f func(context.Context, []int64, []int64) error) *MockITenantServiceBatchAssignTenantsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BatchDelete mocks base method.
func (m *MockITenantService) BatchDelete(ctx context.Context, ids []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockITenantServiceMockRecorder) BatchDelete(ctx, ids any) *MockITenantServiceBatchDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockITenantService)(nil).BatchDelete), ctx, ids)
	return &MockITenantServiceBatchDeleteCall{Call: call}
}

// MockITenantServiceBatchDeleteCall wrap *gomock.Call
type MockITenantServiceBatchDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceBatchDeleteCall) Return(arg0 error) *MockITenantServiceBatchDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceBatchDeleteCall) Do(f func(context.Context, []int64) error) *MockITenantServiceBatchDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceBatchDeleteCall) DoAndReturn(f func(context.Context, []int64) error) *MockITenantServiceBatchDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BatchInitPersonalTenant mocks base method.
func (m *MockITenantService) BatchInitPersonalTenant(ctx context.Context, users []domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchInitPersonalTenant", ctx, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchInitPersonalTenant indicates an expected call of BatchInitPersonalTenant.
func (mr *MockITenantServiceMockRecorder) BatchInitPersonalTenant(ctx, users any) *MockITenantServiceBatchInitPersonalTenantCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInitPersonalTenant", reflect.TypeOf((*MockITenantService)(nil).BatchInitPersonalTenant), ctx, users)
	return &MockITenantServiceBatchInitPersonalTenantCall{Call: call}
}

// MockITenantServiceBatchInitPersonalTenantCall wrap *gomock.Call
type MockITenantServiceBatchInitPersonalTenantCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceBatchInitPersonalTenantCall) Return(arg0 error) *MockITenantServiceBatchInitPersonalTenantCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceBatchInitPersonalTenantCall) Do(f func(context.Context, []domain.User) error) *MockITenantServiceBatchInitPersonalTenantCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceBatchInitPersonalTenantCall) DoAndReturn(f func(context.Context, []domain.User) error) *MockITenantServiceBatchInitPersonalTenantCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BatchRemoveMembers mocks base method.
func (m *MockITenantService) BatchRemoveMembers(ctx context.Context, userIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchRemoveMembers", ctx, userIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchRemoveMembers indicates an expected call of BatchRemoveMembers.
func (mr *MockITenantServiceMockRecorder) BatchRemoveMembers(ctx, userIDs any) *MockITenantServiceBatchRemoveMembersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchRemoveMembers", reflect.TypeOf((*MockITenantService)(nil).BatchRemoveMembers), ctx, userIDs)
	return &MockITenantServiceBatchRemoveMembersCall{Call: call}
}

// MockITenantServiceBatchRemoveMembersCall wrap *gomock.Call
type MockITenantServiceBatchRemoveMembersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceBatchRemoveMembersCall) Return(arg0 error) *MockITenantServiceBatchRemoveMembersCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceBatchRemoveMembersCall) Do(f func(context.Context, []int64) error) *MockITenantServiceBatchRemoveMembersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceBatchRemoveMembersCall) DoAndReturn(f func(context.Context, []int64) error) *MockITenantServiceBatchRemoveMembersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BatchUnassignTenants mocks base method.
func (m *MockITenantService) BatchUnassignTenants(ctx context.Context, userIDs, tenantIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUnassignTenants", ctx, userIDs, tenantIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUnassignTenants indicates an expected call of BatchUnassignTenants.
func (mr *MockITenantServiceMockRecorder) BatchUnassignTenants(ctx, userIDs, tenantIDs any) *MockITenantServiceBatchUnassignTenantsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUnassignTenants", reflect.TypeOf((*MockITenantService)(nil).BatchUnassignTenants), ctx, userIDs, tenantIDs)
	return &MockITenantServiceBatchUnassignTenantsCall{Call: call}
}

// MockITenantServiceBatchUnassignTenantsCall wrap *gomock.Call
type MockITenantServiceBatchUnassignTenantsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceBatchUnassignTenantsCall) Return(arg0 error) *MockITenantServiceBatchUnassignTenantsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceBatchUnassignTenantsCall) Do(f func(context.Context, []int64, []int64) error) *MockITenantServiceBatchUnassignTenantsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceBatchUnassignTenantsCall) DoAndReturn(f func(context.Context, []int64, []int64) error) *MockITenantServiceBatchUnassignTenantsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CheckUserTenantAccess mocks base method.
func (m *MockITenantService) CheckUserTenantAccess(ctx context.Context, userId int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserTenantAccess", ctx, userId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserTenantAccess indicates an expected call of CheckUserTenantAccess.
func (mr *MockITenantServiceMockRecorder) CheckUserTenantAccess(ctx, userId any) *MockITenantServiceCheckUserTenantAccessCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserTenantAccess", reflect.TypeOf((*MockITenantService)(nil).CheckUserTenantAccess), ctx, userId)
	return &MockITenantServiceCheckUserTenantAccessCall{Call: call}
}

// MockITenantServiceCheckUserTenantAccessCall wrap *gomock.Call
type MockITenantServiceCheckUserTenantAccessCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceCheckUserTenantAccessCall) Return(arg0 bool, arg1 error) *MockITenantServiceCheckUserTenantAccessCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceCheckUserTenantAccessCall) Do(f func(context.Context, int64) (bool, error)) *MockITenantServiceCheckUserTenantAccessCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceCheckUserTenantAccessCall) DoAndReturn(f func(context.Context, int64) (bool, error)) *MockITenantServiceCheckUserTenantAccessCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CheckUsersInTenant mocks base method.
func (m *MockITenantService) CheckUsersInTenant(ctx context.Context, userIds []int64) (map[int64]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUsersInTenant", ctx, userIds)
	ret0, _ := ret[0].(map[int64]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUsersInTenant indicates an expected call of CheckUsersInTenant.
func (mr *MockITenantServiceMockRecorder) CheckUsersInTenant(ctx, userIds any) *MockITenantServiceCheckUsersInTenantCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUsersInTenant", reflect.TypeOf((*MockITenantService)(nil).CheckUsersInTenant), ctx, userIds)
	return &MockITenantServiceCheckUsersInTenantCall{Call: call}
}

// MockITenantServiceCheckUsersInTenantCall wrap *gomock.Call
type MockITenantServiceCheckUsersInTenantCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceCheckUsersInTenantCall) Return(arg0 map[int64]bool, arg1 error) *MockITenantServiceCheckUsersInTenantCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceCheckUsersInTenantCall) Do(f func(context.Context, []int64) (map[int64]bool, error)) *MockITenantServiceCheckUsersInTenantCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceCheckUsersInTenantCall) DoAndReturn(f func(context.Context, []int64) (map[int64]bool, error)) *MockITenantServiceCheckUsersInTenantCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateTenant mocks base method.
func (m *MockITenantService) CreateTenant(ctx context.Context, name, code, username string, userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenant", ctx, name, code, username, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenant indicates an expected call of CreateTenant.
func (mr *MockITenantServiceMockRecorder) CreateTenant(ctx, name, code, username, userID any) *MockITenantServiceCreateTenantCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenant", reflect.TypeOf((*MockITenantService)(nil).CreateTenant), ctx, name, code, username, userID)
	return &MockITenantServiceCreateTenantCall{Call: call}
}

// MockITenantServiceCreateTenantCall wrap *gomock.Call
type MockITenantServiceCreateTenantCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceCreateTenantCall) Return(arg0 int64, arg1 error) *MockITenantServiceCreateTenantCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceCreateTenantCall) Do(f func(context.Context, string, string, string, int64) (int64, error)) *MockITenantServiceCreateTenantCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceCreateTenantCall) DoAndReturn(f func(context.Context, string, string, string, int64) (int64, error)) *MockITenantServiceCreateTenantCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockITenantService) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockITenantServiceMockRecorder) Delete(ctx, id any) *MockITenantServiceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockITenantService)(nil).Delete), ctx, id)
	return &MockITenantServiceDeleteCall{Call: call}
}

// MockITenantServiceDeleteCall wrap *gomock.Call
type MockITenantServiceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceDeleteCall) Return(arg0 error) *MockITenantServiceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceDeleteCall) Do(f func(context.Context, int64) error) *MockITenantServiceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceDeleteCall) DoAndReturn(f func(context.Context, int64) error) *MockITenantServiceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAttachedTenantsWithFilter mocks base method.
func (m *MockITenantService) GetAttachedTenantsWithFilter(ctx context.Context, userId, tid, offset, limit int64, keyword string) ([]domain.Tenant, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachedTenantsWithFilter", ctx, userId, tid, offset, limit, keyword)
	ret0, _ := ret[0].([]domain.Tenant)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAttachedTenantsWithFilter indicates an expected call of GetAttachedTenantsWithFilter.
func (mr *MockITenantServiceMockRecorder) GetAttachedTenantsWithFilter(ctx, userId, tid, offset, limit, keyword any) *MockITenantServiceGetAttachedTenantsWithFilterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachedTenantsWithFilter", reflect.TypeOf((*MockITenantService)(nil).GetAttachedTenantsWithFilter), ctx, userId, tid, offset, limit, keyword)
	return &MockITenantServiceGetAttachedTenantsWithFilterCall{Call: call}
}

// MockITenantServiceGetAttachedTenantsWithFilterCall wrap *gomock.Call
type MockITenantServiceGetAttachedTenantsWithFilterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceGetAttachedTenantsWithFilterCall) Return(arg0 []domain.Tenant, arg1 int64, arg2 error) *MockITenantServiceGetAttachedTenantsWithFilterCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceGetAttachedTenantsWithFilterCall) Do(f func(context.Context, int64, int64, int64, int64, string) ([]domain.Tenant, int64, error)) *MockITenantServiceGetAttachedTenantsWithFilterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceGetAttachedTenantsWithFilterCall) DoAndReturn(f func(context.Context, int64, int64, int64, int64, string) ([]domain.Tenant, int64, error)) *MockITenantServiceGetAttachedTenantsWithFilterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockITenantService) GetByID(ctx context.Context, id int64) (domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockITenantServiceMockRecorder) GetByID(ctx, id any) *MockITenantServiceGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockITenantService)(nil).GetByID), ctx, id)
	return &MockITenantServiceGetByIDCall{Call: call}
}

// MockITenantServiceGetByIDCall wrap *gomock.Call
type MockITenantServiceGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceGetByIDCall) Return(arg0 domain.Tenant, arg1 error) *MockITenantServiceGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceGetByIDCall) Do(f func(context.Context, int64) (domain.Tenant, error)) *MockITenantServiceGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceGetByIDCall) DoAndReturn(f func(context.Context, int64) (domain.Tenant, error)) *MockITenantServiceGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetTenantsByUserId mocks base method.
func (m *MockITenantService) GetTenantsByUserId(ctx context.Context, userId int64) ([]domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantsByUserId", ctx, userId)
	ret0, _ := ret[0].([]domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantsByUserId indicates an expected call of GetTenantsByUserId.
func (mr *MockITenantServiceMockRecorder) GetTenantsByUserId(ctx, userId any) *MockITenantServiceGetTenantsByUserIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantsByUserId", reflect.TypeOf((*MockITenantService)(nil).GetTenantsByUserId), ctx, userId)
	return &MockITenantServiceGetTenantsByUserIdCall{Call: call}
}

// MockITenantServiceGetTenantsByUserIdCall wrap *gomock.Call
type MockITenantServiceGetTenantsByUserIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceGetTenantsByUserIdCall) Return(arg0 []domain.Tenant, arg1 error) *MockITenantServiceGetTenantsByUserIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceGetTenantsByUserIdCall) Do(f func(context.Context, int64) ([]domain.Tenant, error)) *MockITenantServiceGetTenantsByUserIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceGetTenantsByUserIdCall) DoAndReturn(f func(context.Context, int64) ([]domain.Tenant, error)) *MockITenantServiceGetTenantsByUserIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// InitPersonalTenant mocks base method.
func (m *MockITenantService) InitPersonalTenant(ctx context.Context, userId int64, username string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitPersonalTenant", ctx, userId, username)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitPersonalTenant indicates an expected call of InitPersonalTenant.
func (mr *MockITenantServiceMockRecorder) InitPersonalTenant(ctx, userId, username any) *MockITenantServiceInitPersonalTenantCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitPersonalTenant", reflect.TypeOf((*MockITenantService)(nil).InitPersonalTenant), ctx, userId, username)
	return &MockITenantServiceInitPersonalTenantCall{Call: call}
}

// MockITenantServiceInitPersonalTenantCall wrap *gomock.Call
type MockITenantServiceInitPersonalTenantCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceInitPersonalTenantCall) Return(arg0 int64, arg1 error) *MockITenantServiceInitPersonalTenantCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceInitPersonalTenantCall) Do(f func(context.Context, int64, string) (int64, error)) *MockITenantServiceInitPersonalTenantCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceInitPersonalTenantCall) DoAndReturn(f func(context.Context, int64, string) (int64, error)) *MockITenantServiceInitPersonalTenantCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockITenantService) List(ctx context.Context, offset, limit int64, keyword string) ([]domain.Tenant, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit, keyword)
	ret0, _ := ret[0].([]domain.Tenant)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockITenantServiceMockRecorder) List(ctx, offset, limit, keyword any) *MockITenantServiceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockITenantService)(nil).List), ctx, offset, limit, keyword)
	return &MockITenantServiceListCall{Call: call}
}

// MockITenantServiceListCall wrap *gomock.Call
type MockITenantServiceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceListCall) Return(arg0 []domain.Tenant, arg1 int64, arg2 error) *MockITenantServiceListCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceListCall) Do(f func(context.Context, int64, int64, string) ([]domain.Tenant, int64, error)) *MockITenantServiceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceListCall) DoAndReturn(f func(context.Context, int64, int64, string) ([]domain.Tenant, int64, error)) *MockITenantServiceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListBindsByUserIds mocks base method.
func (m *MockITenantService) ListBindsByUserIds(ctx context.Context, userIds []int64) (map[int64]domain.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBindsByUserIds", ctx, userIds)
	ret0, _ := ret[0].(map[int64]domain.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBindsByUserIds indicates an expected call of ListBindsByUserIds.
func (mr *MockITenantServiceMockRecorder) ListBindsByUserIds(ctx, userIds any) *MockITenantServiceListBindsByUserIdsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBindsByUserIds", reflect.TypeOf((*MockITenantService)(nil).ListBindsByUserIds), ctx, userIds)
	return &MockITenantServiceListBindsByUserIdsCall{Call: call}
}

// MockITenantServiceListBindsByUserIdsCall wrap *gomock.Call
type MockITenantServiceListBindsByUserIdsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceListBindsByUserIdsCall) Return(arg0 map[int64]domain.Membership, arg1 error) *MockITenantServiceListBindsByUserIdsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceListBindsByUserIdsCall) Do(f func(context.Context, []int64) (map[int64]domain.Membership, error)) *MockITenantServiceListBindsByUserIdsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceListBindsByUserIdsCall) DoAndReturn(f func(context.Context, []int64) (map[int64]domain.Membership, error)) *MockITenantServiceListBindsByUserIdsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListByIDs mocks base method.
func (m *MockITenantService) ListByIDs(ctx context.Context, ids []int64) ([]domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIDs", ctx, ids)
	ret0, _ := ret[0].([]domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIDs indicates an expected call of ListByIDs.
func (mr *MockITenantServiceMockRecorder) ListByIDs(ctx, ids any) *MockITenantServiceListByIDsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIDs", reflect.TypeOf((*MockITenantService)(nil).ListByIDs), ctx, ids)
	return &MockITenantServiceListByIDsCall{Call: call}
}

// MockITenantServiceListByIDsCall wrap *gomock.Call
type MockITenantServiceListByIDsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceListByIDsCall) Return(arg0 []domain.Tenant, arg1 error) *MockITenantServiceListByIDsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceListByIDsCall) Do(f func(context.Context, []int64) ([]domain.Tenant, error)) *MockITenantServiceListByIDsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceListByIDsCall) DoAndReturn(f func(context.Context, []int64) ([]domain.Tenant, error)) *MockITenantServiceListByIDsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListMembers mocks base method.
func (m *MockITenantService) ListMembers(ctx context.Context, offset, limit int64, keyword string) ([]domain.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, offset, limit, keyword)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockITenantServiceMockRecorder) ListMembers(ctx, offset, limit, keyword any) *MockITenantServiceListMembersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockITenantService)(nil).ListMembers), ctx, offset, limit, keyword)
	return &MockITenantServiceListMembersCall{Call: call}
}

// MockITenantServiceListMembersCall wrap *gomock.Call
type MockITenantServiceListMembersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceListMembersCall) Return(arg0 []domain.User, arg1 int64, arg2 error) *MockITenantServiceListMembersCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceListMembersCall) Do(f func(context.Context, int64, int64, string) ([]domain.User, int64, error)) *MockITenantServiceListMembersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceListMembersCall) DoAndReturn(f func(context.Context, int64, int64, string) ([]domain.User, int64, error)) *MockITenantServiceListMembersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveMember mocks base method.
func (m *MockITenantService) RemoveMember(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockITenantServiceMockRecorder) RemoveMember(ctx, userID any) *MockITenantServiceRemoveMemberCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockITenantService)(nil).RemoveMember), ctx, userID)
	return &MockITenantServiceRemoveMemberCall{Call: call}
}

// MockITenantServiceRemoveMemberCall wrap *gomock.Call
type MockITenantServiceRemoveMemberCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceRemoveMemberCall) Return(arg0 error) *MockITenantServiceRemoveMemberCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceRemoveMemberCall) Do(f func(context.Context, int64) error) *MockITenantServiceRemoveMemberCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceRemoveMemberCall) DoAndReturn(f func(context.Context, int64) error) *MockITenantServiceRemoveMemberCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockITenantService) Update(ctx context.Context, t domain.Tenant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockITenantServiceMockRecorder) Update(ctx, t any) *MockITenantServiceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockITenantService)(nil).Update), ctx, t)
	return &MockITenantServiceUpdateCall{Call: call}
}

// MockITenantServiceUpdateCall wrap *gomock.Call
type MockITenantServiceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceUpdateCall) Return(arg0 error) *MockITenantServiceUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceUpdateCall) Do(f func(context.Context, domain.Tenant) error) *MockITenantServiceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceUpdateCall) DoAndReturn(f func(context.Context, domain.Tenant) error) *MockITenantServiceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateLastActiveTenant mocks base method.
func (m *MockITenantService) UpdateLastActiveTenant(ctx context.Context, uid, tid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastActiveTenant", ctx, uid, tid)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastActiveTenant indicates an expected call of UpdateLastActiveTenant.
func (mr *MockITenantServiceMockRecorder) UpdateLastActiveTenant(ctx, uid, tid any) *MockITenantServiceUpdateLastActiveTenantCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastActiveTenant", reflect.TypeOf((*MockITenantService)(nil).UpdateLastActiveTenant), ctx, uid, tid)
	return &MockITenantServiceUpdateLastActiveTenantCall{Call: call}
}

// MockITenantServiceUpdateLastActiveTenantCall wrap *gomock.Call
type MockITenantServiceUpdateLastActiveTenantCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITenantServiceUpdateLastActiveTenantCall) Return(arg0 error) *MockITenantServiceUpdateLastActiveTenantCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITenantServiceUpdateLastActiveTenantCall) Do(f func(context.Context, int64, int64) error) *MockITenantServiceUpdateLastActiveTenantCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITenantServiceUpdateLastActiveTenantCall) DoAndReturn(f func(context.Context, int64, int64) error) *MockITenantServiceUpdateLastActiveTenantCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
