// Code generated by MockGen. DO NOT EDIT.
// Source: ./role.go
//
// Generated by this command:
//
//	mockgen -source=./role.go -package=rolemocks -destination=./mocks/role.mock.go -typed IRoleService
//

// Package rolemocks is a generated GoMock package.
package rolemocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eiam/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIRoleService is a mock of IRoleService interface.
type MockIRoleService struct {
	ctrl     *gomock.Controller
	recorder *MockIRoleServiceMockRecorder
	isgomock struct{}
}

// MockIRoleServiceMockRecorder is the mock recorder for MockIRoleService.
type MockIRoleServiceMockRecorder struct {
	mock *MockIRoleService
}

// NewMockIRoleService creates a new mock instance.
func NewMockIRoleService(ctrl *gomock.Controller) *MockIRoleService {
	mock := &MockIRoleService{ctrl: ctrl}
	mock.recorder = &MockIRoleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRoleService) EXPECT() *MockIRoleServiceMockRecorder {
	return m.recorder
}

// BatchDelete mocks base method.
func (m *MockIRoleService) BatchDelete(ctx context.Context, ids []int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ctx, ids)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockIRoleServiceMockRecorder) BatchDelete(ctx, ids any) *MockIRoleServiceBatchDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockIRoleService)(nil).BatchDelete), ctx, ids)
	return &MockIRoleServiceBatchDeleteCall{Call: call}
}

// MockIRoleServiceBatchDeleteCall wrap *gomock.Call
type MockIRoleServiceBatchDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIRoleServiceBatchDeleteCall) Return(arg0 int64, arg1 error) *MockIRoleServiceBatchDeleteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIRoleServiceBatchDeleteCall) Do(f func(context.Context, []int64) (int64, error)) *MockIRoleServiceBatchDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIRoleServiceBatchDeleteCall) DoAndReturn(f func(context.Context, []int64) (int64, error)) *MockIRoleServiceBatchDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CountByKeyword mocks base method.
func (m *MockIRoleService) CountByKeyword(ctx context.Context, keyword string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByKeyword", ctx, keyword)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByKeyword indicates an expected call of CountByKeyword.
func (mr *MockIRoleServiceMockRecorder) CountByKeyword(ctx, keyword any) *MockIRoleServiceCountByKeywordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByKeyword", reflect.TypeOf((*MockIRoleService)(nil).CountByKeyword), ctx, keyword)
	return &MockIRoleServiceCountByKeywordCall{Call: call}
}

// MockIRoleServiceCountByKeywordCall wrap *gomock.Call
type MockIRoleServiceCountByKeywordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIRoleServiceCountByKeywordCall) Return(arg0 int64, arg1 error) *MockIRoleServiceCountByKeywordCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIRoleServiceCountByKeywordCall) Do(f func(context.Context, string) (int64, error)) *MockIRoleServiceCountByKeywordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIRoleServiceCountByKeywordCall) DoAndReturn(f func(context.Context, string) (int64, error)) *MockIRoleServiceCountByKeywordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockIRoleService) Create(ctx context.Context, r domain.Role) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIRoleServiceMockRecorder) Create(ctx, r any) *MockIRoleServiceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIRoleService)(nil).Create), ctx, r)
	return &MockIRoleServiceCreateCall{Call: call}
}

// MockIRoleServiceCreateCall wrap *gomock.Call
type MockIRoleServiceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIRoleServiceCreateCall) Return(arg0 int64, arg1 error) *MockIRoleServiceCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIRoleServiceCreateCall) Do(f func(context.Context, domain.Role) (int64, error)) *MockIRoleServiceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIRoleServiceCreateCall) DoAndReturn(f func(context.Context, domain.Role) (int64, error)) *MockIRoleServiceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockIRoleService) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIRoleServiceMockRecorder) Delete(ctx, id any) *MockIRoleServiceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIRoleService)(nil).Delete), ctx, id)
	return &MockIRoleServiceDeleteCall{Call: call}
}

// MockIRoleServiceDeleteCall wrap *gomock.Call
type MockIRoleServiceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIRoleServiceDeleteCall) Return(arg0 error) *MockIRoleServiceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIRoleServiceDeleteCall) Do(f func(context.Context, int64) error) *MockIRoleServiceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIRoleServiceDeleteCall) DoAndReturn(f func(context.Context, int64) error) *MockIRoleServiceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByCode mocks base method.
func (m *MockIRoleService) GetByCode(ctx context.Context, code string) (domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockIRoleServiceMockRecorder) GetByCode(ctx, code any) *MockIRoleServiceGetByCodeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockIRoleService)(nil).GetByCode), ctx, code)
	return &MockIRoleServiceGetByCodeCall{Call: call}
}

// MockIRoleServiceGetByCodeCall wrap *gomock.Call
type MockIRoleServiceGetByCodeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIRoleServiceGetByCodeCall) Return(arg0 domain.Role, arg1 error) *MockIRoleServiceGetByCodeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIRoleServiceGetByCodeCall) Do(f func(context.Context, string) (domain.Role, error)) *MockIRoleServiceGetByCodeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIRoleServiceGetByCodeCall) DoAndReturn(f func(context.Context, string) (domain.Role, error)) *MockIRoleServiceGetByCodeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByIDs mocks base method.
func (m *MockIRoleService) GetByIDs(ctx context.Context, ids []int64) ([]domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].([]domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockIRoleServiceMockRecorder) GetByIDs(ctx, ids any) *MockIRoleServiceGetByIDsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockIRoleService)(nil).GetByIDs), ctx, ids)
	return &MockIRoleServiceGetByIDsCall{Call: call}
}

// MockIRoleServiceGetByIDsCall wrap *gomock.Call
type MockIRoleServiceGetByIDsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIRoleServiceGetByIDsCall) Return(arg0 []domain.Role, arg1 error) *MockIRoleServiceGetByIDsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIRoleServiceGetByIDsCall) Do(f func(context.Context, []int64) ([]domain.Role, error)) *MockIRoleServiceGetByIDsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIRoleServiceGetByIDsCall) DoAndReturn(f func(context.Context, []int64) ([]domain.Role, error)) *MockIRoleServiceGetByIDsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockIRoleService) List(ctx context.Context, offset, limit int64) ([]domain.Role, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit)
	ret0, _ := ret[0].([]domain.Role)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockIRoleServiceMockRecorder) List(ctx, offset, limit any) *MockIRoleServiceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIRoleService)(nil).List), ctx, offset, limit)
	return &MockIRoleServiceListCall{Call: call}
}

// MockIRoleServiceListCall wrap *gomock.Call
type MockIRoleServiceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIRoleServiceListCall) Return(arg0 []domain.Role, arg1 int64, arg2 error) *MockIRoleServiceListCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIRoleServiceListCall) Do(f func(context.Context, int64, int64) ([]domain.Role, int64, error)) *MockIRoleServiceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIRoleServiceListCall) DoAndReturn(f func(context.Context, int64, int64) ([]domain.Role, int64, error)) *MockIRoleServiceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListAttachedRoles mocks base method.
func (m *MockIRoleService) ListAttachedRoles(ctx context.Context, username string, offset, limit int64, keyword string) ([]domain.Role, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAttachedRoles", ctx, username, offset, limit, keyword)
	ret0, _ := ret[0].([]domain.Role)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAttachedRoles indicates an expected call of ListAttachedRoles.
func (mr *MockIRoleServiceMockRecorder) ListAttachedRoles(ctx, username, offset, limit, keyword any) *MockIRoleServiceListAttachedRolesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAttachedRoles", reflect.TypeOf((*MockIRoleService)(nil).ListAttachedRoles), ctx, username, offset, limit, keyword)
	return &MockIRoleServiceListAttachedRolesCall{Call: call}
}

// MockIRoleServiceListAttachedRolesCall wrap *gomock.Call
type MockIRoleServiceListAttachedRolesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIRoleServiceListAttachedRolesCall) Return(arg0 []domain.Role, arg1 int64, arg2 error) *MockIRoleServiceListAttachedRolesCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIRoleServiceListAttachedRolesCall) Do(f func(context.Context, string, int64, int64, string) ([]domain.Role, int64, error)) *MockIRoleServiceListAttachedRolesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIRoleServiceListAttachedRolesCall) DoAndReturn(f func(context.Context, string, int64, int64, string) ([]domain.Role, int64, error)) *MockIRoleServiceListAttachedRolesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListByIncludeCodes mocks base method.
func (m *MockIRoleService) ListByIncludeCodes(ctx context.Context, codes []string) ([]domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIncludeCodes", ctx, codes)
	ret0, _ := ret[0].([]domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIncludeCodes indicates an expected call of ListByIncludeCodes.
func (mr *MockIRoleServiceMockRecorder) ListByIncludeCodes(ctx, codes any) *MockIRoleServiceListByIncludeCodesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIncludeCodes", reflect.TypeOf((*MockIRoleService)(nil).ListByIncludeCodes), ctx, codes)
	return &MockIRoleServiceListByIncludeCodesCall{Call: call}
}

// MockIRoleServiceListByIncludeCodesCall wrap *gomock.Call
type MockIRoleServiceListByIncludeCodesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIRoleServiceListByIncludeCodesCall) Return(arg0 []domain.Role, arg1 error) *MockIRoleServiceListByIncludeCodesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIRoleServiceListByIncludeCodesCall) Do(f func(context.Context, []string) ([]domain.Role, error)) *MockIRoleServiceListByIncludeCodesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIRoleServiceListByIncludeCodesCall) DoAndReturn(f func(context.Context, []string) ([]domain.Role, error)) *MockIRoleServiceListByIncludeCodesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Search mocks base method.
func (m *MockIRoleService) Search(ctx context.Context, keyword string, offset, limit int64) ([]domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, keyword, offset, limit)
	ret0, _ := ret[0].([]domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockIRoleServiceMockRecorder) Search(ctx, keyword, offset, limit any) *MockIRoleServiceSearchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockIRoleService)(nil).Search), ctx, keyword, offset, limit)
	return &MockIRoleServiceSearchCall{Call: call}
}

// MockIRoleServiceSearchCall wrap *gomock.Call
type MockIRoleServiceSearchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIRoleServiceSearchCall) Return(arg0 []domain.Role, arg1 error) *MockIRoleServiceSearchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIRoleServiceSearchCall) Do(f func(context.Context, string, int64, int64) ([]domain.Role, error)) *MockIRoleServiceSearchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIRoleServiceSearchCall) DoAndReturn(f func(context.Context, string, int64, int64) ([]domain.Role, error)) *MockIRoleServiceSearchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockIRoleService) Update(ctx context.Context, r domain.Role) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, r)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIRoleServiceMockRecorder) Update(ctx, r any) *MockIRoleServiceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIRoleService)(nil).Update), ctx, r)
	return &MockIRoleServiceUpdateCall{Call: call}
}

// MockIRoleServiceUpdateCall wrap *gomock.Call
type MockIRoleServiceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIRoleServiceUpdateCall) Return(arg0 int64, arg1 error) *MockIRoleServiceUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIRoleServiceUpdateCall) Do(f func(context.Context, domain.Role) (int64, error)) *MockIRoleServiceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIRoleServiceUpdateCall) DoAndReturn(f func(context.Context, domain.Role) (int64, error)) *MockIRoleServiceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateInlinePolicies mocks base method.
func (m *MockIRoleService) UpdateInlinePolicies(ctx context.Context, roleCode string, policies []domain.Policy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInlinePolicies", ctx, roleCode, policies)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInlinePolicies indicates an expected call of UpdateInlinePolicies.
func (mr *MockIRoleServiceMockRecorder) UpdateInlinePolicies(ctx, roleCode, policies any) *MockIRoleServiceUpdateInlinePoliciesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInlinePolicies", reflect.TypeOf((*MockIRoleService)(nil).UpdateInlinePolicies), ctx, roleCode, policies)
	return &MockIRoleServiceUpdateInlinePoliciesCall{Call: call}
}

// MockIRoleServiceUpdateInlinePoliciesCall wrap *gomock.Call
type MockIRoleServiceUpdateInlinePoliciesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIRoleServiceUpdateInlinePoliciesCall) Return(arg0 error) *MockIRoleServiceUpdateInlinePoliciesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIRoleServiceUpdateInlinePoliciesCall) Do(f func(context.Context, string, []domain.Policy) error) *MockIRoleServiceUpdateInlinePoliciesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIRoleServiceUpdateInlinePoliciesCall) DoAndReturn(f func(context.Context, string, []domain.Policy) error) *MockIRoleServiceUpdateInlinePoliciesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
