// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package testioc

import (
	"github.com/Havens-blog/e-iam/internal/pkg/searcher"
	"github.com/Havens-blog/e-iam/internal/repository"
	"github.com/Havens-blog/e-iam/internal/repository/cache"
	"github.com/Havens-blog/e-iam/internal/repository/dao"
	"github.com/Havens-blog/e-iam/internal/service/permission"
	"github.com/Havens-blog/e-iam/internal/service/permission/checker"
	"github.com/Havens-blog/e-iam/internal/service/policy"
	"github.com/Havens-blog/e-iam/internal/service/resource"
	"github.com/Havens-blog/e-iam/internal/service/role"
	"github.com/Havens-blog/e-iam/internal/service/tenant"
	"github.com/Havens-blog/e-iam/ioc"
)

// Injectors from wire.go:

func InitPermissionSuiteDeps() (*PermissionSuiteDeps, error) {
	db := InitDB()
	syncedEnforcer := ioc.InitCasbin(db)
	iTenantDAO := dao.NewTenantDAO(db)
	iTenantRepository := repository.NewTenantRepository(iTenantDAO)
	iUserDAO := dao.NewUserDAO(db)
	cmdable := ioc.InitRedis()
	iUserCache := cache.NewUserCache(cmdable)
	iUserRepository := repository.NewUserRepository(iUserDAO, iTenantDAO, iUserCache)
	iRoleDAO := dao.NewRoleDAO(db)
	iRoleRepository := repository.NewRoleRepository(iRoleDAO)
	iPolicyDAO := dao.NewPolicyDAO(db)
	iPolicyRepository := repository.NewPolicyRepository(iPolicyDAO)
	iPermissionDAO := dao.NewPermissionDAO(db)
	iPermissionCache := cache.NewPermissionCache(cmdable)
	iPermissionRepository := repository.NewPermissionRepository(iPermissionDAO, iPermissionCache)
	iBoundaryChecker := checker.NewBoundaryChecker(iPermissionRepository)
	iPolicyService := policy.NewPolicyService(iPolicyRepository, iBoundaryChecker)
	iRoleService := role.NewRoleService(iRoleRepository, iPolicyService, iBoundaryChecker, syncedEnforcer)
	iTenantKeyDAO := dao.NewTenantKeyDAO(db)
	iTenantKeyRepository := repository.NewTenantKeyRepository(iTenantKeyDAO)
	iTenantKeyService := tenant.NewTenantKeyService(iTenantKeyRepository)
	iTenantService := tenant.NewTenantService(iTenantRepository, iUserRepository, iRoleService, syncedEnforcer, iTenantKeyService)
	iResourceDAO := dao.NewResourceDAO(db)
	iResourceCache := cache.NewResourceCache(cmdable)
	iResourceRepository := repository.NewResourceRepository(iResourceDAO, iResourceCache)
	iServiceDAO := dao.NewServiceDAO(db)
	iServiceRepository := repository.NewServiceRepository(iServiceDAO)
	iResourceService := resource.NewResourceService(iResourceRepository, iServiceRepository)
	iSubjectRegistry := ProvideTestSubjectRegistry()
	iAuthorizer := ioc.InitOPA()
	iPermissionService := permission.NewPermissionService(syncedEnforcer, iPolicyService, iRoleService, iSubjectRegistry, iResourceService, iPermissionRepository, iAuthorizer, iBoundaryChecker, iTenantRepository)
	permissionSuiteDeps := &PermissionSuiteDeps{
		DB:           db,
		Enforcer:     syncedEnforcer,
		TenantSvc:    iTenantService,
		TenantKeySvc: iTenantKeyService,
		RoleSvc:      iRoleService,
		PolicySvc:    iPolicyService,
		ResourceSvc:  iResourceService,
		PermSvc:      iPermissionService,
	}
	return permissionSuiteDeps, nil
}

// wire.go:

// ProvideTestSubjectRegistry 提供测试环境下空的主体注册中心
func ProvideTestSubjectRegistry() searcher.ISubjectRegistry {
	return searcher.NewSubjectRegistry()
}
