// Code generated by MockGen. DO NOT EDIT.
// Source: ./user.go
//
// Generated by this command:
//
//	mockgen -source=./user.go -package=usermocks -destination=./mocks/user.mock.go -typed IUserService
//

// Package usermocks is a generated GoMock package.
package usermocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Havens-blog/e-iam/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIUserService is a mock of IUserService interface.
type MockIUserService struct {
	ctrl     *gomock.Controller
	recorder *MockIUserServiceMockRecorder
	isgomock struct{}
}

// MockIUserServiceMockRecorder is the mock recorder for MockIUserService.
type MockIUserServiceMockRecorder struct {
	mock *MockIUserService
}

// NewMockIUserService creates a new mock instance.
func NewMockIUserService(ctrl *gomock.Controller) *MockIUserService {
	mock := &MockIUserService{ctrl: ctrl}
	mock.recorder = &MockIUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserService) EXPECT() *MockIUserServiceMockRecorder {
	return m.recorder
}

// AddRoleBind mocks base method.
func (m *MockIUserService) AddRoleBind(ctx context.Context, id int64, roleCodes []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRoleBind", ctx, id, roleCodes)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRoleBind indicates an expected call of AddRoleBind.
func (mr *MockIUserServiceMockRecorder) AddRoleBind(ctx, id, roleCodes any) *MockIUserServiceAddRoleBindCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRoleBind", reflect.TypeOf((*MockIUserService)(nil).AddRoleBind), ctx, id, roleCodes)
	return &MockIUserServiceAddRoleBindCall{Call: call}
}

// MockIUserServiceAddRoleBindCall wrap *gomock.Call
type MockIUserServiceAddRoleBindCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIUserServiceAddRoleBindCall) Return(arg0 int64, arg1 error) *MockIUserServiceAddRoleBindCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIUserServiceAddRoleBindCall) Do(f func(context.Context, int64, []string) (int64, error)) *MockIUserServiceAddRoleBindCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIUserServiceAddRoleBindCall) DoAndReturn(f func(context.Context, int64, []string) (int64, error)) *MockIUserServiceAddRoleBindCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByDepartmentId mocks base method.
func (m *MockIUserService) FindByDepartmentId(ctx context.Context, offset, limit, departmentId int64) ([]domain.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDepartmentId", ctx, offset, limit, departmentId)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByDepartmentId indicates an expected call of FindByDepartmentId.
func (mr *MockIUserServiceMockRecorder) FindByDepartmentId(ctx, offset, limit, departmentId any) *MockIUserServiceFindByDepartmentIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDepartmentId", reflect.TypeOf((*MockIUserService)(nil).FindByDepartmentId), ctx, offset, limit, departmentId)
	return &MockIUserServiceFindByDepartmentIdCall{Call: call}
}

// MockIUserServiceFindByDepartmentIdCall wrap *gomock.Call
type MockIUserServiceFindByDepartmentIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIUserServiceFindByDepartmentIdCall) Return(arg0 []domain.User, arg1 int64, arg2 error) *MockIUserServiceFindByDepartmentIdCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIUserServiceFindByDepartmentIdCall) Do(f func(context.Context, int64, int64, int64) ([]domain.User, int64, error)) *MockIUserServiceFindByDepartmentIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIUserServiceFindByDepartmentIdCall) DoAndReturn(f func(context.Context, int64, int64, int64) ([]domain.User, int64, error)) *MockIUserServiceFindByDepartmentIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByKeywords mocks base method.
func (m *MockIUserService) FindByKeywords(ctx context.Context, offset, limit int64, keyword string) ([]domain.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByKeywords", ctx, offset, limit, keyword)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByKeywords indicates an expected call of FindByKeywords.
func (mr *MockIUserServiceMockRecorder) FindByKeywords(ctx, offset, limit, keyword any) *MockIUserServiceFindByKeywordsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByKeywords", reflect.TypeOf((*MockIUserService)(nil).FindByKeywords), ctx, offset, limit, keyword)
	return &MockIUserServiceFindByKeywordsCall{Call: call}
}

// MockIUserServiceFindByKeywordsCall wrap *gomock.Call
type MockIUserServiceFindByKeywordsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIUserServiceFindByKeywordsCall) Return(arg0 []domain.User, arg1 int64, arg2 error) *MockIUserServiceFindByKeywordsCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIUserServiceFindByKeywordsCall) Do(f func(context.Context, int64, int64, string) ([]domain.User, int64, error)) *MockIUserServiceFindByKeywordsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIUserServiceFindByKeywordsCall) DoAndReturn(f func(context.Context, int64, int64, string) ([]domain.User, int64, error)) *MockIUserServiceFindByKeywordsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOrCreateByLdap mocks base method.
func (m *MockIUserService) FindOrCreateByLdap(ctx context.Context, u domain.User) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreateByLdap", ctx, u)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreateByLdap indicates an expected call of FindOrCreateByLdap.
func (mr *MockIUserServiceMockRecorder) FindOrCreateByLdap(ctx, u any) *MockIUserServiceFindOrCreateByLdapCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreateByLdap", reflect.TypeOf((*MockIUserService)(nil).FindOrCreateByLdap), ctx, u)
	return &MockIUserServiceFindOrCreateByLdapCall{Call: call}
}

// MockIUserServiceFindOrCreateByLdapCall wrap *gomock.Call
type MockIUserServiceFindOrCreateByLdapCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIUserServiceFindOrCreateByLdapCall) Return(arg0 domain.User, arg1 error) *MockIUserServiceFindOrCreateByLdapCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIUserServiceFindOrCreateByLdapCall) Do(f func(context.Context, domain.User) (domain.User, error)) *MockIUserServiceFindOrCreateByLdapCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIUserServiceFindOrCreateByLdapCall) DoAndReturn(f func(context.Context, domain.User) (domain.User, error)) *MockIUserServiceFindOrCreateByLdapCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOrCreateBySystem mocks base method.
func (m *MockIUserService) FindOrCreateBySystem(ctx context.Context, u domain.User) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreateBySystem", ctx, u)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreateBySystem indicates an expected call of FindOrCreateBySystem.
func (mr *MockIUserServiceMockRecorder) FindOrCreateBySystem(ctx, u any) *MockIUserServiceFindOrCreateBySystemCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreateBySystem", reflect.TypeOf((*MockIUserService)(nil).FindOrCreateBySystem), ctx, u)
	return &MockIUserServiceFindOrCreateBySystemCall{Call: call}
}

// MockIUserServiceFindOrCreateBySystemCall wrap *gomock.Call
type MockIUserServiceFindOrCreateBySystemCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIUserServiceFindOrCreateBySystemCall) Return(arg0 domain.User, arg1 error) *MockIUserServiceFindOrCreateBySystemCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIUserServiceFindOrCreateBySystemCall) Do(f func(context.Context, domain.User) (domain.User, error)) *MockIUserServiceFindOrCreateBySystemCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIUserServiceFindOrCreateBySystemCall) DoAndReturn(f func(context.Context, domain.User) (domain.User, error)) *MockIUserServiceFindOrCreateBySystemCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetById mocks base method.
func (m *MockIUserService) GetById(ctx context.Context, id int64) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIUserServiceMockRecorder) GetById(ctx, id any) *MockIUserServiceGetByIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIUserService)(nil).GetById), ctx, id)
	return &MockIUserServiceGetByIdCall{Call: call}
}

// MockIUserServiceGetByIdCall wrap *gomock.Call
type MockIUserServiceGetByIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIUserServiceGetByIdCall) Return(arg0 domain.User, arg1 error) *MockIUserServiceGetByIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIUserServiceGetByIdCall) Do(f func(context.Context, int64) (domain.User, error)) *MockIUserServiceGetByIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIUserServiceGetByIdCall) DoAndReturn(f func(context.Context, int64) (domain.User, error)) *MockIUserServiceGetByIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByUsername mocks base method.
func (m *MockIUserService) GetByUsername(ctx context.Context, username string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", ctx, username)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockIUserServiceMockRecorder) GetByUsername(ctx, username any) *MockIUserServiceGetByUsernameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockIUserService)(nil).GetByUsername), ctx, username)
	return &MockIUserServiceGetByUsernameCall{Call: call}
}

// MockIUserServiceGetByUsernameCall wrap *gomock.Call
type MockIUserServiceGetByUsernameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIUserServiceGetByUsernameCall) Return(arg0 domain.User, arg1 error) *MockIUserServiceGetByUsernameCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIUserServiceGetByUsernameCall) Do(f func(context.Context, string) (domain.User, error)) *MockIUserServiceGetByUsernameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIUserServiceGetByUsernameCall) DoAndReturn(f func(context.Context, string) (domain.User, error)) *MockIUserServiceGetByUsernameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockIUserService) List(ctx context.Context, offset, limit int64) ([]domain.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockIUserServiceMockRecorder) List(ctx, offset, limit any) *MockIUserServiceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIUserService)(nil).List), ctx, offset, limit)
	return &MockIUserServiceListCall{Call: call}
}

// MockIUserServiceListCall wrap *gomock.Call
type MockIUserServiceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIUserServiceListCall) Return(arg0 []domain.User, arg1 int64, arg2 error) *MockIUserServiceListCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIUserServiceListCall) Do(f func(context.Context, int64, int64) ([]domain.User, int64, error)) *MockIUserServiceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIUserServiceListCall) DoAndReturn(f func(context.Context, int64, int64) ([]domain.User, int64, error)) *MockIUserServiceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListByIds mocks base method.
func (m *MockIUserService) ListByIds(ctx context.Context, ids []int64) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIds", ctx, ids)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIds indicates an expected call of ListByIds.
func (mr *MockIUserServiceMockRecorder) ListByIds(ctx, ids any) *MockIUserServiceListByIdsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIds", reflect.TypeOf((*MockIUserService)(nil).ListByIds), ctx, ids)
	return &MockIUserServiceListByIdsCall{Call: call}
}

// MockIUserServiceListByIdsCall wrap *gomock.Call
type MockIUserServiceListByIdsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIUserServiceListByIdsCall) Return(arg0 []domain.User, arg1 error) *MockIUserServiceListByIdsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIUserServiceListByIdsCall) Do(f func(context.Context, []int64) ([]domain.User, error)) *MockIUserServiceListByIdsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIUserServiceListByIdsCall) DoAndReturn(f func(context.Context, []int64) ([]domain.User, error)) *MockIUserServiceListByIdsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Login mocks base method.
func (m *MockIUserService) Login(ctx context.Context, username, password string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, username, password)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockIUserServiceMockRecorder) Login(ctx, username, password any) *MockIUserServiceLoginCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockIUserService)(nil).Login), ctx, username, password)
	return &MockIUserServiceLoginCall{Call: call}
}

// MockIUserServiceLoginCall wrap *gomock.Call
type MockIUserServiceLoginCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIUserServiceLoginCall) Return(arg0 domain.User, arg1 error) *MockIUserServiceLoginCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIUserServiceLoginCall) Do(f func(context.Context, string, string) (domain.User, error)) *MockIUserServiceLoginCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIUserServiceLoginCall) DoAndReturn(f func(context.Context, string, string) (domain.User, error)) *MockIUserServiceLoginCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Signup mocks base method.
func (m *MockIUserService) Signup(ctx context.Context, u domain.User) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signup", ctx, u)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signup indicates an expected call of Signup.
func (mr *MockIUserServiceMockRecorder) Signup(ctx, u any) *MockIUserServiceSignupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signup", reflect.TypeOf((*MockIUserService)(nil).Signup), ctx, u)
	return &MockIUserServiceSignupCall{Call: call}
}

// MockIUserServiceSignupCall wrap *gomock.Call
type MockIUserServiceSignupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIUserServiceSignupCall) Return(arg0 int64, arg1 error) *MockIUserServiceSignupCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIUserServiceSignupCall) Do(f func(context.Context, domain.User) (int64, error)) *MockIUserServiceSignupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIUserServiceSignupCall) DoAndReturn(f func(context.Context, domain.User) (int64, error)) *MockIUserServiceSignupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockIUserService) Update(ctx context.Context, req domain.User) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIUserServiceMockRecorder) Update(ctx, req any) *MockIUserServiceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIUserService)(nil).Update), ctx, req)
	return &MockIUserServiceUpdateCall{Call: call}
}

// MockIUserServiceUpdateCall wrap *gomock.Call
type MockIUserServiceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIUserServiceUpdateCall) Return(arg0 int64, arg1 error) *MockIUserServiceUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIUserServiceUpdateCall) Do(f func(context.Context, domain.User) (int64, error)) *MockIUserServiceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIUserServiceUpdateCall) DoAndReturn(f func(context.Context, domain.User) (int64, error)) *MockIUserServiceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
