// Code generated by eiam permgen. DO NOT EDIT.

package permission

// Audit 安全审计
var Audit = struct {
	Module        string
	ViewAuth      string // 查看认证审计 [租户级]
	ViewOperation string // 查看操作审计 [租户级]
}{
	Module:        "iam:audit",
	ViewAuth:      "iam:audit:view_auth",
	ViewOperation: "iam:audit:view_operation",
}

// Department 部门管理
var Department = struct {
	Module  string
	Add     string // 创建部门 [租户级]
	Assign  string // 分配部门成员 [租户级]
	Delete  string // 删除部门 [租户级]
	Edit    string // 修改部门 [租户级]
	Get     string // 部门详情 [租户级]
	Members string // 部门成员列表 [租户级]
	Remove  string // 移除部门成员 [租户级]
	View    string // 部门树 [租户级]
}{
	Module:  "iam:department",
	Add:     "iam:department:add",
	Assign:  "iam:department:assign",
	Delete:  "iam:department:delete",
	Edit:    "iam:department:edit",
	Get:     "iam:department:get",
	Members: "iam:department:members",
	Remove:  "iam:department:remove",
	View:    "iam:department:view",
}

// Group 用户分组
var Group = struct {
	Module        string
	Add           string // 创建用户组 [租户级]
	AssignMembers string // 分配组成员 [租户级]
	AssignRole    string // 用户组分配角色 [租户级]
	Delete        string // 删除用户组 [租户级]
	Edit          string // 修改用户组 [租户级]
	Get           string // 用户组详情 [租户级]
	Members       string // 组成员列表 [租户级]
	RemoveMembers string // 移除组成员 [租户级]
	RemoveRole    string // 用户组解绑角色 [租户级]
	Roles         string // 查看用户组角色 [租户级]
	View          string // 用户组列表 [租户级]
}{
	Module:        "iam:group",
	Add:           "iam:group:add",
	AssignMembers: "iam:group:assign_members",
	AssignRole:    "iam:group:assign_role",
	Delete:        "iam:group:delete",
	Edit:          "iam:group:edit",
	Get:           "iam:group:get",
	Members:       "iam:group:members",
	RemoveMembers: "iam:group:remove_members",
	RemoveRole:    "iam:group:remove_role",
	Roles:         "iam:group:roles",
	View:          "iam:group:view",
}

// IdentitySource 身份源管理
var IdentitySource = struct {
	Module string
	Delete string // 删除身份源 [系统级]
	Detail string // 身份源详情 [系统级]
	Save   string // 保存身份源 [系统级]
	Test   string // 测试身份源连接 [系统级]
	Toggle string // 切换启用状态 [系统级]
	View   string // 身份源列表 [系统级]
}{
	Module: "iam:identity_source",
	Delete: "iam:identity_source:delete",
	Detail: "iam:identity_source:detail",
	Save:   "iam:identity_source:save",
	Test:   "iam:identity_source:test",
	Toggle: "iam:identity_source:toggle",
	View:   "iam:identity_source:view",
}

// Idp 统一身份提供商
var Idp = struct {
	Module         string
	Create         string // 创建接入应用 [租户级]
	Delete         string // 删除接入应用 [租户级]
	Detail         string // 接入应用详情 [租户级]
	List           string // 接入应用列表 [租户级]
	ResetSecret    string // 重置应用密钥 [租户级]
	SamlDescriptor string // 获取SAML接入描述符 [租户级]
	SamlRotateCert string // 轮换SAML证书 [租户级]
	Update         string // 更新接入应用 [租户级]
}{
	Module:         "iam:idp",
	Create:         "iam:idp:create",
	Delete:         "iam:idp:delete",
	Detail:         "iam:idp:detail",
	List:           "iam:idp:list",
	ResetSecret:    "iam:idp:reset_secret",
	SamlDescriptor: "iam:idp:saml_descriptor",
	SamlRotateCert: "iam:idp:saml_rotate_cert",
	Update:         "iam:idp:update",
}

// Invitation 成员治理
var Invitation = struct {
	Module        string
	Add           string // 创建邀请 [租户级]
	BatchDelete   string // 批量撤回邀请 [租户级]
	Delete        string // 撤回邀请 [租户级]
	HandleRequest string // 处理申请 [租户级]
	View          string // 邀请列表 [租户级]
	ViewRequests  string // 申请列表 [租户级]
}{
	Module:        "iam:invitation",
	Add:           "iam:invitation:add",
	BatchDelete:   "iam:invitation:batch_delete",
	Delete:        "iam:invitation:delete",
	HandleRequest: "iam:invitation:handle_request",
	View:          "iam:invitation:view",
	ViewRequests:  "iam:invitation:view_requests",
}

// Permission 权限管理
var Permission = struct {
	Module             string
	Manifest           string // 权限资产清单 [租户级]
	MenusByUrns        string // 批量根据 URN 查询菜单详情 [租户级 · 静默]
	SearchSubjects     string // 搜索授权主体 [租户级]
	ViewAuthorizations string // 授权治理列表 [租户级]
}{
	Module:             "iam:permission",
	Manifest:           "iam:permission:manifest",
	MenusByUrns:        "iam:permission:menus_by_urns",
	SearchSubjects:     "iam:permission:search_subjects",
	ViewAuthorizations: "iam:permission:view_authorizations",
}

// Policy 策略管理
var Policy = struct {
	Module      string
	Add         string // 创建策略 [租户级]
	BatchAttach string // 批量绑定策略 [租户级]
	BatchDelete string // 批量删除策略 [租户级]
	BatchDetach string // 批量解绑策略 [租户级]
	Delete      string // 删除策略 [租户级]
	Detach      string // 解绑策略 [租户级]
	Edit        string // 修改策略 [租户级]
	Get         string // 策略详情 [租户级]
	View        string // 策略列表 [租户级]
}{
	Module:      "iam:policy",
	Add:         "iam:policy:add",
	BatchAttach: "iam:policy:batch_attach",
	BatchDelete: "iam:policy:batch_delete",
	BatchDetach: "iam:policy:batch_detach",
	Delete:      "iam:policy:delete",
	Detach:      "iam:policy:detach",
	Edit:        "iam:policy:edit",
	Get:         "iam:policy:get",
	View:        "iam:policy:view",
}

// Role 角色管理
var Role = struct {
	Module           string
	Add              string // 创建角色 [租户级]
	AddParent        string // 添加父角色 [租户级]
	Analysis         string // 分析内联策略 [租户级]
	BatchAssign      string // 批量分配角色 [租户级]
	BatchDelete      string // 批量删除角色 [租户级]
	BatchUnassign    string // 批量移除角色 [租户级]
	Delete           string // 删除角色 [租户级]
	Edit             string // 修改角色 [租户级]
	Get              string // 角色详情 [租户级]
	RemoveParent     string // 移除父角色 [租户级]
	Unassign         string // 移除角色分配 [租户级]
	View             string // 角色列表 [租户级]
	ViewMine         string // 查看个人角色 [租户级]
	ViewParents      string // 获取父角色 [租户级]
	ViewRoleGroups   string // 查询角色关联分组 [租户级 · 跨域: group]
	ViewRoleMembers  string // 角色关联用户列表 [租户级 · 跨域: user]
	ViewRolePolicies string // 查询角色策略 [租户级 · 跨域: policy]
}{
	Module:           "iam:role",
	Add:              "iam:role:add",
	AddParent:        "iam:role:add_parent",
	Analysis:         "iam:role:analysis",
	BatchAssign:      "iam:role:batch_assign",
	BatchDelete:      "iam:role:batch_delete",
	BatchUnassign:    "iam:role:batch_unassign",
	Delete:           "iam:role:delete",
	Edit:             "iam:role:edit",
	Get:              "iam:role:get",
	RemoveParent:     "iam:role:remove_parent",
	Unassign:         "iam:role:unassign",
	View:             "iam:role:view",
	ViewMine:         "iam:role:view_mine",
	ViewParents:      "iam:role:view_parents",
	ViewRoleGroups:   "iam:role:view_role_groups",
	ViewRoleMembers:  "iam:role:view_role_members",
	ViewRolePolicies: "iam:role:view_role_policies",
}

// Tenant 租户管理
var Tenant = struct {
	Module        string
	Add           string // 创建租户空间 [系统级]
	Assign        string // 分配租户成员 [系统级]
	BatchAssign   string // 批量分配租户成员 [系统级]
	BatchDelete   string // 批量删除租户 [系统级]
	BatchUnassign string // 批量移除租户成员 [系统级]
	Delete        string // 删除租户空间 [系统级]
	Edit          string // 修改租户信息 [系统级]
	Get           string // 查看租户详情 [系统级]
	Switch        string // 切换租户空间 [租户级 · 静默]
	Unassign      string // 移除租户成员 [系统级]
	View          string // 全量租户列表 [系统级]
	ViewByIds     string // 批量查询租户 [系统级]
	ViewMembers   string // 查看租户成员 [租户级]
	ViewMine      string // 查询我的租户列表 [租户级 · 静默]
}{
	Module:        "iam:tenant",
	Add:           "iam:tenant:add",
	Assign:        "iam:tenant:assign",
	BatchAssign:   "iam:tenant:batch_assign",
	BatchDelete:   "iam:tenant:batch_delete",
	BatchUnassign: "iam:tenant:batch_unassign",
	Delete:        "iam:tenant:delete",
	Edit:          "iam:tenant:edit",
	Get:           "iam:tenant:get",
	Switch:        "iam:tenant:switch",
	Unassign:      "iam:tenant:unassign",
	View:          "iam:tenant:view",
	ViewByIds:     "iam:tenant:view_by_ids",
	ViewMembers:   "iam:tenant:view_members",
	ViewMine:      "iam:tenant:view_mine",
}

// User 用户管理
var User = struct {
	Module           string
	Add              string // 创建用户 [租户级]
	BatchDelete      string // 批量删除用户 [租户级]
	Delete           string // 删除用户 [租户级]
	Edit             string // 修改用户 [租户级]
	Get              string // 用户详情 [租户级]
	LdapRefresh      string // 刷新 LDAP 缓存 [租户级 · 子级]
	LdapSearch       string // 搜索 LDAP [租户级 · 子级]
	LdapSync         string // 同步 LDAP [租户级 · 子级]
	Logout           string // 退出登录 [租户级 · 静默]
	ManageIdentity   string // 治理外部身份 [租户级]
	Profile          string // 个人信息 [租户级 · 静默]
	UnbindIdentity   string // 解绑外部身份 [租户级]
	View             string // 用户列表 [租户级]
	ViewUserGroups   string // 查询用户所属分组 [租户级 · 跨域: group]
	ViewUserPolicies string // 查询用户策略 [租户级 · 跨域: policy]
	ViewUserRoles    string // 查询用户角色 [租户级 · 跨域: role]
	ViewUserTenants  string // 查询用户所属租户 [租户级 · 跨域: tenant]
}{
	Module:           "iam:user",
	Add:              "iam:user:add",
	BatchDelete:      "iam:user:batch_delete",
	Delete:           "iam:user:delete",
	Edit:             "iam:user:edit",
	Get:              "iam:user:get",
	LdapRefresh:      "iam:user.ldap:refresh",
	LdapSearch:       "iam:user.ldap:search",
	LdapSync:         "iam:user.ldap:sync",
	Logout:           "iam:user:logout",
	ManageIdentity:   "iam:user:manage_identity",
	Profile:          "iam:user:profile",
	UnbindIdentity:   "iam:user:unbind_identity",
	View:             "iam:user:view",
	ViewUserGroups:   "iam:user:view_user_groups",
	ViewUserPolicies: "iam:user:view_user_policies",
	ViewUserRoles:    "iam:user:view_user_roles",
	ViewUserTenants:  "iam:user:view_user_tenants",
}
