// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/idp/claims/resolver.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/idp/claims/resolver.go -destination=internal/service/idp/claims/mocks/resolver.mock.go -package=claimsmocks
//

// Package claimsmocks is a generated GoMock package.
package claimsmocks

import (
	context "context"
	reflect "reflect"

	claims "github.com/Duke1616/eiam/internal/service/idp/claims"
	gomock "go.uber.org/mock/gomock"
)

// MockIClaimsResolver is a mock of IClaimsResolver interface.
type MockIClaimsResolver struct {
	ctrl     *gomock.Controller
	recorder *MockIClaimsResolverMockRecorder
	isgomock struct{}
}

// MockIClaimsResolverMockRecorder is the mock recorder for MockIClaimsResolver.
type MockIClaimsResolverMockRecorder struct {
	mock *MockIClaimsResolver
}

// NewMockIClaimsResolver creates a new mock instance.
func NewMockIClaimsResolver(ctrl *gomock.Controller) *MockIClaimsResolver {
	mock := &MockIClaimsResolver{ctrl: ctrl}
	mock.recorder = &MockIClaimsResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClaimsResolver) EXPECT() *MockIClaimsResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockIClaimsResolver) Resolve(ctx context.Context, ref claims.IdentityRef, opts ...claims.ResolveOption) (claims.Claims, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, ref}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Resolve", varargs...)
	ret0, _ := ret[0].(claims.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockIClaimsResolverMockRecorder) Resolve(ctx, ref any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, ref}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockIClaimsResolver)(nil).Resolve), varargs...)
}
