// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source=./service.go -package=samlmocks -destination=./mocks/service.mock.go -typed ISamlService
//

// Package samlmocks is a generated GoMock package.
package samlmocks

import (
	context "context"
	reflect "reflect"

	saml "github.com/Duke1616/eiam/internal/service/idp/saml"
	saml0 "github.com/crewjam/saml"
	gomock "go.uber.org/mock/gomock"
)

// MockISamlService is a mock of ISamlService interface.
type MockISamlService struct {
	ctrl     *gomock.Controller
	recorder *MockISamlServiceMockRecorder
	isgomock struct{}
}

// MockISamlServiceMockRecorder is the mock recorder for MockISamlService.
type MockISamlServiceMockRecorder struct {
	mock *MockISamlService
}

// NewMockISamlService creates a new mock instance.
func NewMockISamlService(ctrl *gomock.Controller) *MockISamlService {
	mock := &MockISamlService{ctrl: ctrl}
	mock.recorder = &MockISamlServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISamlService) EXPECT() *MockISamlServiceMockRecorder {
	return m.recorder
}

// BuildLoginResponse mocks base method.
func (m *MockISamlService) BuildLoginResponse(ctx context.Context, req saml.SamlLoginRequest) (*saml.SamlLoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildLoginResponse", ctx, req)
	ret0, _ := ret[0].(*saml.SamlLoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildLoginResponse indicates an expected call of BuildLoginResponse.
func (mr *MockISamlServiceMockRecorder) BuildLoginResponse(ctx, req any) *MockISamlServiceBuildLoginResponseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildLoginResponse", reflect.TypeOf((*MockISamlService)(nil).BuildLoginResponse), ctx, req)
	return &MockISamlServiceBuildLoginResponseCall{Call: call}
}

// MockISamlServiceBuildLoginResponseCall wrap *gomock.Call
type MockISamlServiceBuildLoginResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockISamlServiceBuildLoginResponseCall) Return(arg0 *saml.SamlLoginResult, arg1 error) *MockISamlServiceBuildLoginResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockISamlServiceBuildLoginResponseCall) Do(f func(context.Context, saml.SamlLoginRequest) (*saml.SamlLoginResult, error)) *MockISamlServiceBuildLoginResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockISamlServiceBuildLoginResponseCall) DoAndReturn(f func(context.Context, saml.SamlLoginRequest) (*saml.SamlLoginResult, error)) *MockISamlServiceBuildLoginResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetCertificateDetail mocks base method.
func (m *MockISamlService) GetCertificateDetail() saml.CertificateDetail {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCertificateDetail")
	ret0, _ := ret[0].(saml.CertificateDetail)
	return ret0
}

// GetCertificateDetail indicates an expected call of GetCertificateDetail.
func (mr *MockISamlServiceMockRecorder) GetCertificateDetail() *MockISamlServiceGetCertificateDetailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCertificateDetail", reflect.TypeOf((*MockISamlService)(nil).GetCertificateDetail))
	return &MockISamlServiceGetCertificateDetailCall{Call: call}
}

// MockISamlServiceGetCertificateDetailCall wrap *gomock.Call
type MockISamlServiceGetCertificateDetailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockISamlServiceGetCertificateDetailCall) Return(arg0 saml.CertificateDetail) *MockISamlServiceGetCertificateDetailCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockISamlServiceGetCertificateDetailCall) Do(f func() saml.CertificateDetail) *MockISamlServiceGetCertificateDetailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockISamlServiceGetCertificateDetailCall) DoAndReturn(f func() saml.CertificateDetail) *MockISamlServiceGetCertificateDetailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetCertificatePEM mocks base method.
func (m *MockISamlService) GetCertificatePEM() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCertificatePEM")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCertificatePEM indicates an expected call of GetCertificatePEM.
func (mr *MockISamlServiceMockRecorder) GetCertificatePEM() *MockISamlServiceGetCertificatePEMCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCertificatePEM", reflect.TypeOf((*MockISamlService)(nil).GetCertificatePEM))
	return &MockISamlServiceGetCertificatePEMCall{Call: call}
}

// MockISamlServiceGetCertificatePEMCall wrap *gomock.Call
type MockISamlServiceGetCertificatePEMCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockISamlServiceGetCertificatePEMCall) Return(arg0 string) *MockISamlServiceGetCertificatePEMCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockISamlServiceGetCertificatePEMCall) Do(f func() string) *MockISamlServiceGetCertificatePEMCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockISamlServiceGetCertificatePEMCall) DoAndReturn(f func() string) *MockISamlServiceGetCertificatePEMCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetMetadataXML mocks base method.
func (m *MockISamlService) GetMetadataXML(ctx context.Context, issuerURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadataXML", ctx, issuerURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadataXML indicates an expected call of GetMetadataXML.
func (mr *MockISamlServiceMockRecorder) GetMetadataXML(ctx, issuerURL any) *MockISamlServiceGetMetadataXMLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadataXML", reflect.TypeOf((*MockISamlService)(nil).GetMetadataXML), ctx, issuerURL)
	return &MockISamlServiceGetMetadataXMLCall{Call: call}
}

// MockISamlServiceGetMetadataXMLCall wrap *gomock.Call
type MockISamlServiceGetMetadataXMLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockISamlServiceGetMetadataXMLCall) Return(arg0 string, arg1 error) *MockISamlServiceGetMetadataXMLCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockISamlServiceGetMetadataXMLCall) Do(f func(context.Context, string) (string, error)) *MockISamlServiceGetMetadataXMLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockISamlServiceGetMetadataXMLCall) DoAndReturn(f func(context.Context, string) (string, error)) *MockISamlServiceGetMetadataXMLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ParseAuthnRequest mocks base method.
func (m *MockISamlService) ParseAuthnRequest(rawReq string, isRedirect bool) (*saml0.AuthnRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAuthnRequest", rawReq, isRedirect)
	ret0, _ := ret[0].(*saml0.AuthnRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseAuthnRequest indicates an expected call of ParseAuthnRequest.
func (mr *MockISamlServiceMockRecorder) ParseAuthnRequest(rawReq, isRedirect any) *MockISamlServiceParseAuthnRequestCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAuthnRequest", reflect.TypeOf((*MockISamlService)(nil).ParseAuthnRequest), rawReq, isRedirect)
	return &MockISamlServiceParseAuthnRequestCall{Call: call}
}

// MockISamlServiceParseAuthnRequestCall wrap *gomock.Call
type MockISamlServiceParseAuthnRequestCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockISamlServiceParseAuthnRequestCall) Return(arg0 *saml0.AuthnRequest, arg1 error) *MockISamlServiceParseAuthnRequestCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockISamlServiceParseAuthnRequestCall) Do(f func(string, bool) (*saml0.AuthnRequest, error)) *MockISamlServiceParseAuthnRequestCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockISamlServiceParseAuthnRequestCall) DoAndReturn(f func(string, bool) (*saml0.AuthnRequest, error)) *MockISamlServiceParseAuthnRequestCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RotateCertificate mocks base method.
func (m *MockISamlService) RotateCertificate(ctx context.Context, validityYears int) (*saml.CertificateDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateCertificate", ctx, validityYears)
	ret0, _ := ret[0].(*saml.CertificateDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateCertificate indicates an expected call of RotateCertificate.
func (mr *MockISamlServiceMockRecorder) RotateCertificate(ctx, validityYears any) *MockISamlServiceRotateCertificateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateCertificate", reflect.TypeOf((*MockISamlService)(nil).RotateCertificate), ctx, validityYears)
	return &MockISamlServiceRotateCertificateCall{Call: call}
}

// MockISamlServiceRotateCertificateCall wrap *gomock.Call
type MockISamlServiceRotateCertificateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockISamlServiceRotateCertificateCall) Return(arg0 *saml.CertificateDetail, arg1 error) *MockISamlServiceRotateCertificateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockISamlServiceRotateCertificateCall) Do(f func(context.Context, int) (*saml.CertificateDetail, error)) *MockISamlServiceRotateCertificateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockISamlServiceRotateCertificateCall) DoAndReturn(f func(context.Context, int) (*saml.CertificateDetail, error)) *MockISamlServiceRotateCertificateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
