// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Duke1616/eiam/pkg/redisx (interfaces: IStreamQueue)
//
// Generated by this command:
//
//	mockgen -package=redisxmocks -destination=./mocks/stream.mock.go github.com/Duke1616/eiam/pkg/redisx IStreamQueue
//

// Package redisxmocks is a generated GoMock package.
package redisxmocks

import (
	context "context"
	reflect "reflect"
	time "time"

	redisx "github.com/Duke1616/eiam/pkg/redisx"
	gomock "go.uber.org/mock/gomock"
)

// MockIStreamQueue is a mock of IStreamQueue interface.
type MockIStreamQueue[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockIStreamQueueMockRecorder[T]
	isgomock struct{}
}

// MockIStreamQueueMockRecorder is the mock recorder for MockIStreamQueue.
type MockIStreamQueueMockRecorder[T any] struct {
	mock *MockIStreamQueue[T]
}

// NewMockIStreamQueue creates a new mock instance.
func NewMockIStreamQueue[T any](ctrl *gomock.Controller) *MockIStreamQueue[T] {
	mock := &MockIStreamQueue[T]{ctrl: ctrl}
	mock.recorder = &MockIStreamQueueMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStreamQueue[T]) EXPECT() *MockIStreamQueueMockRecorder[T] {
	return m.recorder
}

// Ack mocks base method.
func (m *MockIStreamQueue[T]) Ack(ctx context.Context, stream, group string, ids ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, stream, group}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Ack", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ack indicates an expected call of Ack.
func (mr *MockIStreamQueueMockRecorder[T]) Ack(ctx, stream, group any, ids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, stream, group}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ack", reflect.TypeOf((*MockIStreamQueue[T])(nil).Ack), varargs...)
}

// AutoClaim mocks base method.
func (m *MockIStreamQueue[T]) AutoClaim(ctx context.Context, stream, group, consumer string, minIdle time.Duration, start string, count int64) ([]redisx.Message[T], string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutoClaim", ctx, stream, group, consumer, minIdle, start, count)
	ret0, _ := ret[0].([]redisx.Message[T])
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AutoClaim indicates an expected call of AutoClaim.
func (mr *MockIStreamQueueMockRecorder[T]) AutoClaim(ctx, stream, group, consumer, minIdle, start, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoClaim", reflect.TypeOf((*MockIStreamQueue[T])(nil).AutoClaim), ctx, stream, group, consumer, minIdle, start, count)
}

// InitGroup mocks base method.
func (m *MockIStreamQueue[T]) InitGroup(ctx context.Context, stream, group string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitGroup", ctx, stream, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitGroup indicates an expected call of InitGroup.
func (mr *MockIStreamQueueMockRecorder[T]) InitGroup(ctx, stream, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitGroup", reflect.TypeOf((*MockIStreamQueue[T])(nil).InitGroup), ctx, stream, group)
}

// Publish mocks base method.
func (m *MockIStreamQueue[T]) Publish(ctx context.Context, stream string, payload T, opts ...redisx.PublishOption) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, stream, payload}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Publish", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockIStreamQueueMockRecorder[T]) Publish(ctx, stream, payload any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, stream, payload}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockIStreamQueue[T])(nil).Publish), varargs...)
}

// ReadGroup mocks base method.
func (m *MockIStreamQueue[T]) ReadGroup(ctx context.Context, stream, group, consumer string, count int64, block time.Duration) ([]redisx.Message[T], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadGroup", ctx, stream, group, consumer, count, block)
	ret0, _ := ret[0].([]redisx.Message[T])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadGroup indicates an expected call of ReadGroup.
func (mr *MockIStreamQueueMockRecorder[T]) ReadGroup(ctx, stream, group, consumer, count, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadGroup", reflect.TypeOf((*MockIStreamQueue[T])(nil).ReadGroup), ctx, stream, group, consumer, count, block)
}
