// Code generated by MockGen. DO NOT EDIT.
// Source: ./application.go
//
// Generated by this command:
//
//	mockgen -source=./application.go -package=idpmocks -destination=./mocks/application.mock.go -typed IService
//

// Package idpmocks is a generated GoMock package.
package idpmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eiam/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
	isgomock struct{}
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIService) Create(ctx context.Context, app domain.Application) (domain.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, app)
	ret0, _ := ret[0].(domain.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIServiceMockRecorder) Create(ctx, app any) *MockIServiceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIService)(nil).Create), ctx, app)
	return &MockIServiceCreateCall{Call: call}
}

// MockIServiceCreateCall wrap *gomock.Call
type MockIServiceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIServiceCreateCall) Return(arg0 domain.Application, arg1 error) *MockIServiceCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIServiceCreateCall) Do(f func(context.Context, domain.Application) (domain.Application, error)) *MockIServiceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIServiceCreateCall) DoAndReturn(f func(context.Context, domain.Application) (domain.Application, error)) *MockIServiceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockIService) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIServiceMockRecorder) Delete(ctx, id any) *MockIServiceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIService)(nil).Delete), ctx, id)
	return &MockIServiceDeleteCall{Call: call}
}

// MockIServiceDeleteCall wrap *gomock.Call
type MockIServiceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIServiceDeleteCall) Return(arg0 error) *MockIServiceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIServiceDeleteCall) Do(f func(context.Context, int64) error) *MockIServiceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIServiceDeleteCall) DoAndReturn(f func(context.Context, int64) error) *MockIServiceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByClientID mocks base method.
func (m *MockIService) GetByClientID(ctx context.Context, clientID string) (domain.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByClientID", ctx, clientID)
	ret0, _ := ret[0].(domain.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByClientID indicates an expected call of GetByClientID.
func (mr *MockIServiceMockRecorder) GetByClientID(ctx, clientID any) *MockIServiceGetByClientIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByClientID", reflect.TypeOf((*MockIService)(nil).GetByClientID), ctx, clientID)
	return &MockIServiceGetByClientIDCall{Call: call}
}

// MockIServiceGetByClientIDCall wrap *gomock.Call
type MockIServiceGetByClientIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIServiceGetByClientIDCall) Return(arg0 domain.Application, arg1 error) *MockIServiceGetByClientIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIServiceGetByClientIDCall) Do(f func(context.Context, string) (domain.Application, error)) *MockIServiceGetByClientIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIServiceGetByClientIDCall) DoAndReturn(f func(context.Context, string) (domain.Application, error)) *MockIServiceGetByClientIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockIService) GetByID(ctx context.Context, id int64) (domain.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIServiceMockRecorder) GetByID(ctx, id any) *MockIServiceGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIService)(nil).GetByID), ctx, id)
	return &MockIServiceGetByIDCall{Call: call}
}

// MockIServiceGetByIDCall wrap *gomock.Call
type MockIServiceGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIServiceGetByIDCall) Return(arg0 domain.Application, arg1 error) *MockIServiceGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIServiceGetByIDCall) Do(f func(context.Context, int64) (domain.Application, error)) *MockIServiceGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIServiceGetByIDCall) DoAndReturn(f func(context.Context, int64) (domain.Application, error)) *MockIServiceGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockIService) List(ctx context.Context, offset, limit int) ([]domain.Application, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit)
	ret0, _ := ret[0].([]domain.Application)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockIServiceMockRecorder) List(ctx, offset, limit any) *MockIServiceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIService)(nil).List), ctx, offset, limit)
	return &MockIServiceListCall{Call: call}
}

// MockIServiceListCall wrap *gomock.Call
type MockIServiceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIServiceListCall) Return(arg0 []domain.Application, arg1 int64, arg2 error) *MockIServiceListCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIServiceListCall) Do(f func(context.Context, int, int) ([]domain.Application, int64, error)) *MockIServiceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIServiceListCall) DoAndReturn(f func(context.Context, int, int) ([]domain.Application, int64, error)) *MockIServiceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ResetSecret mocks base method.
func (m *MockIService) ResetSecret(ctx context.Context, id int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetSecret", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetSecret indicates an expected call of ResetSecret.
func (mr *MockIServiceMockRecorder) ResetSecret(ctx, id any) *MockIServiceResetSecretCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetSecret", reflect.TypeOf((*MockIService)(nil).ResetSecret), ctx, id)
	return &MockIServiceResetSecretCall{Call: call}
}

// MockIServiceResetSecretCall wrap *gomock.Call
type MockIServiceResetSecretCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIServiceResetSecretCall) Return(arg0 string, arg1 error) *MockIServiceResetSecretCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIServiceResetSecretCall) Do(f func(context.Context, int64) (string, error)) *MockIServiceResetSecretCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIServiceResetSecretCall) DoAndReturn(f func(context.Context, int64) (string, error)) *MockIServiceResetSecretCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockIService) Update(ctx context.Context, app domain.Application) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, app)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIServiceMockRecorder) Update(ctx, app any) *MockIServiceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIService)(nil).Update), ctx, app)
	return &MockIServiceUpdateCall{Call: call}
}

// MockIServiceUpdateCall wrap *gomock.Call
type MockIServiceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIServiceUpdateCall) Return(arg0 error) *MockIServiceUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIServiceUpdateCall) Do(f func(context.Context, domain.Application) error) *MockIServiceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIServiceUpdateCall) DoAndReturn(f func(context.Context, domain.Application) error) *MockIServiceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
