// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Duke1616/eiam/internal/service/resource (interfaces: IResourceService)
//
// Generated by this command:
//
//	mockgen -package=resourcemocks -destination=./mocks/resource.mock.go github.com/Duke1616/eiam/internal/service/resource IResourceService
//

// Package resourcemocks is a generated GoMock package.
package resourcemocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eiam/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIResourceService is a mock of IResourceService interface.
type MockIResourceService struct {
	ctrl     *gomock.Controller
	recorder *MockIResourceServiceMockRecorder
	isgomock struct{}
}

// MockIResourceServiceMockRecorder is the mock recorder for MockIResourceService.
type MockIResourceServiceMockRecorder struct {
	mock *MockIResourceService
}

// NewMockIResourceService creates a new mock instance.
func NewMockIResourceService(ctrl *gomock.Controller) *MockIResourceService {
	mock := &MockIResourceService{ctrl: ctrl}
	mock.recorder = &MockIResourceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIResourceService) EXPECT() *MockIResourceServiceMockRecorder {
	return m.recorder
}

// BatchRegisterServices mocks base method.
func (m *MockIResourceService) BatchRegisterServices(ctx context.Context, services []domain.Service) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchRegisterServices", ctx, services)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchRegisterServices indicates an expected call of BatchRegisterServices.
func (mr *MockIResourceServiceMockRecorder) BatchRegisterServices(ctx, services any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchRegisterServices", reflect.TypeOf((*MockIResourceService)(nil).BatchRegisterServices), ctx, services)
}

// CreateAPI mocks base method.
func (m *MockIResourceService) CreateAPI(ctx context.Context, a domain.API) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAPI", ctx, a)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAPI indicates an expected call of CreateAPI.
func (mr *MockIResourceServiceMockRecorder) CreateAPI(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAPI", reflect.TypeOf((*MockIResourceService)(nil).CreateAPI), ctx, a)
}

// FindAPIByPath mocks base method.
func (m *MockIResourceService) FindAPIByPath(ctx context.Context, service, method, path string) (domain.API, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAPIByPath", ctx, service, method, path)
	ret0, _ := ret[0].(domain.API)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAPIByPath indicates an expected call of FindAPIByPath.
func (mr *MockIResourceServiceMockRecorder) FindAPIByPath(ctx, service, method, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAPIByPath", reflect.TypeOf((*MockIResourceService)(nil).FindAPIByPath), ctx, service, method, path)
}

// GetServiceByCode mocks base method.
func (m *MockIResourceService) GetServiceByCode(ctx context.Context, code string) (domain.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceByCode", ctx, code)
	ret0, _ := ret[0].(domain.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceByCode indicates an expected call of GetServiceByCode.
func (mr *MockIResourceServiceMockRecorder) GetServiceByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceByCode", reflect.TypeOf((*MockIResourceService)(nil).GetServiceByCode), ctx, code)
}

// ListAllMenus mocks base method.
func (m *MockIResourceService) ListAllMenus(ctx context.Context) ([]domain.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllMenus", ctx)
	ret0, _ := ret[0].([]domain.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllMenus indicates an expected call of ListAllMenus.
func (mr *MockIResourceServiceMockRecorder) ListAllMenus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllMenus", reflect.TypeOf((*MockIResourceService)(nil).ListAllMenus), ctx)
}

// ListServices mocks base method.
func (m *MockIResourceService) ListServices(ctx context.Context) ([]domain.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServices", ctx)
	ret0, _ := ret[0].([]domain.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServices indicates an expected call of ListServices.
func (mr *MockIResourceServiceMockRecorder) ListServices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServices", reflect.TypeOf((*MockIResourceService)(nil).ListServices), ctx)
}

// ReorderMenu mocks base method.
func (m *MockIResourceService) ReorderMenu(ctx context.Context, id, targetPid, targetPosition int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderMenu", ctx, id, targetPid, targetPosition)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReorderMenu indicates an expected call of ReorderMenu.
func (mr *MockIResourceServiceMockRecorder) ReorderMenu(ctx, id, targetPid, targetPosition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderMenu", reflect.TypeOf((*MockIResourceService)(nil).ReorderMenu), ctx, id, targetPid, targetPosition)
}

// SyncMenus mocks base method.
func (m *MockIResourceService) SyncMenus(ctx context.Context, menus domain.MenuTree) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncMenus", ctx, menus)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncMenus indicates an expected call of SyncMenus.
func (mr *MockIResourceServiceMockRecorder) SyncMenus(ctx, menus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncMenus", reflect.TypeOf((*MockIResourceService)(nil).SyncMenus), ctx, menus)
}
