// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source=./service.go -package=casmocks -destination=./mocks/service.mock.go -typed ICasService
//

// Package casmocks is a generated GoMock package.
package casmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eiam/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockICasService is a mock of ICasService interface.
type MockICasService struct {
	ctrl     *gomock.Controller
	recorder *MockICasServiceMockRecorder
	isgomock struct{}
}

// MockICasServiceMockRecorder is the mock recorder for MockICasService.
type MockICasServiceMockRecorder struct {
	mock *MockICasService
}

// NewMockICasService creates a new mock instance.
func NewMockICasService(ctrl *gomock.Controller) *MockICasService {
	mock := &MockICasService{ctrl: ctrl}
	mock.recorder = &MockICasServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICasService) EXPECT() *MockICasServiceMockRecorder {
	return m.recorder
}

// BuildFailureJSON mocks base method.
func (m *MockICasService) BuildFailureJSON(code, message string) *domain.CasJsonResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildFailureJSON", code, message)
	ret0, _ := ret[0].(*domain.CasJsonResponse)
	return ret0
}

// BuildFailureJSON indicates an expected call of BuildFailureJSON.
func (mr *MockICasServiceMockRecorder) BuildFailureJSON(code, message any) *MockICasServiceBuildFailureJSONCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildFailureJSON", reflect.TypeOf((*MockICasService)(nil).BuildFailureJSON), code, message)
	return &MockICasServiceBuildFailureJSONCall{Call: call}
}

// MockICasServiceBuildFailureJSONCall wrap *gomock.Call
type MockICasServiceBuildFailureJSONCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockICasServiceBuildFailureJSONCall) Return(arg0 *domain.CasJsonResponse) *MockICasServiceBuildFailureJSONCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockICasServiceBuildFailureJSONCall) Do(f func(string, string) *domain.CasJsonResponse) *MockICasServiceBuildFailureJSONCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockICasServiceBuildFailureJSONCall) DoAndReturn(f func(string, string) *domain.CasJsonResponse) *MockICasServiceBuildFailureJSONCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BuildFailureXML mocks base method.
func (m *MockICasService) BuildFailureXML(code, message string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildFailureXML", code, message)
	ret0, _ := ret[0].(string)
	return ret0
}

// BuildFailureXML indicates an expected call of BuildFailureXML.
func (mr *MockICasServiceMockRecorder) BuildFailureXML(code, message any) *MockICasServiceBuildFailureXMLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildFailureXML", reflect.TypeOf((*MockICasService)(nil).BuildFailureXML), code, message)
	return &MockICasServiceBuildFailureXMLCall{Call: call}
}

// MockICasServiceBuildFailureXMLCall wrap *gomock.Call
type MockICasServiceBuildFailureXMLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockICasServiceBuildFailureXMLCall) Return(arg0 string) *MockICasServiceBuildFailureXMLCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockICasServiceBuildFailureXMLCall) Do(f func(string, string) string) *MockICasServiceBuildFailureXMLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockICasServiceBuildFailureXMLCall) DoAndReturn(f func(string, string) string) *MockICasServiceBuildFailureXMLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BuildSuccessJSON mocks base method.
func (m *MockICasService) BuildSuccessJSON(result *domain.CasValidationResult) *domain.CasJsonResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildSuccessJSON", result)
	ret0, _ := ret[0].(*domain.CasJsonResponse)
	return ret0
}

// BuildSuccessJSON indicates an expected call of BuildSuccessJSON.
func (mr *MockICasServiceMockRecorder) BuildSuccessJSON(result any) *MockICasServiceBuildSuccessJSONCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildSuccessJSON", reflect.TypeOf((*MockICasService)(nil).BuildSuccessJSON), result)
	return &MockICasServiceBuildSuccessJSONCall{Call: call}
}

// MockICasServiceBuildSuccessJSONCall wrap *gomock.Call
type MockICasServiceBuildSuccessJSONCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockICasServiceBuildSuccessJSONCall) Return(arg0 *domain.CasJsonResponse) *MockICasServiceBuildSuccessJSONCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockICasServiceBuildSuccessJSONCall) Do(f func(*domain.CasValidationResult) *domain.CasJsonResponse) *MockICasServiceBuildSuccessJSONCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockICasServiceBuildSuccessJSONCall) DoAndReturn(f func(*domain.CasValidationResult) *domain.CasJsonResponse) *MockICasServiceBuildSuccessJSONCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BuildSuccessXML mocks base method.
func (m *MockICasService) BuildSuccessXML(result *domain.CasValidationResult) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildSuccessXML", result)
	ret0, _ := ret[0].(string)
	return ret0
}

// BuildSuccessXML indicates an expected call of BuildSuccessXML.
func (mr *MockICasServiceMockRecorder) BuildSuccessXML(result any) *MockICasServiceBuildSuccessXMLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildSuccessXML", reflect.TypeOf((*MockICasService)(nil).BuildSuccessXML), result)
	return &MockICasServiceBuildSuccessXMLCall{Call: call}
}

// MockICasServiceBuildSuccessXMLCall wrap *gomock.Call
type MockICasServiceBuildSuccessXMLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockICasServiceBuildSuccessXMLCall) Return(arg0 string) *MockICasServiceBuildSuccessXMLCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockICasServiceBuildSuccessXMLCall) Do(f func(*domain.CasValidationResult) string) *MockICasServiceBuildSuccessXMLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockICasServiceBuildSuccessXMLCall) DoAndReturn(f func(*domain.CasValidationResult) string) *MockICasServiceBuildSuccessXMLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GenerateTicket mocks base method.
func (m *MockICasService) GenerateTicket(ctx context.Context, userID, tenantID int64, username, service string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTicket", ctx, userID, tenantID, username, service)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTicket indicates an expected call of GenerateTicket.
func (mr *MockICasServiceMockRecorder) GenerateTicket(ctx, userID, tenantID, username, service any) *MockICasServiceGenerateTicketCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTicket", reflect.TypeOf((*MockICasService)(nil).GenerateTicket), ctx, userID, tenantID, username, service)
	return &MockICasServiceGenerateTicketCall{Call: call}
}

// MockICasServiceGenerateTicketCall wrap *gomock.Call
type MockICasServiceGenerateTicketCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockICasServiceGenerateTicketCall) Return(arg0 string, arg1 error) *MockICasServiceGenerateTicketCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockICasServiceGenerateTicketCall) Do(f func(context.Context, int64, int64, string, string) (string, error)) *MockICasServiceGenerateTicketCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockICasServiceGenerateTicketCall) DoAndReturn(f func(context.Context, int64, int64, string, string) (string, error)) *MockICasServiceGenerateTicketCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ValidatePlainText mocks base method.
func (m *MockICasService) ValidatePlainText(ctx context.Context, ticket, service string) (bool, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePlainText", ctx, ticket, service)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// ValidatePlainText indicates an expected call of ValidatePlainText.
func (mr *MockICasServiceMockRecorder) ValidatePlainText(ctx, ticket, service any) *MockICasServiceValidatePlainTextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePlainText", reflect.TypeOf((*MockICasService)(nil).ValidatePlainText), ctx, ticket, service)
	return &MockICasServiceValidatePlainTextCall{Call: call}
}

// MockICasServiceValidatePlainTextCall wrap *gomock.Call
type MockICasServiceValidatePlainTextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockICasServiceValidatePlainTextCall) Return(arg0 bool, arg1 string) *MockICasServiceValidatePlainTextCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockICasServiceValidatePlainTextCall) Do(f func(context.Context, string, string) (bool, string)) *MockICasServiceValidatePlainTextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockICasServiceValidatePlainTextCall) DoAndReturn(f func(context.Context, string, string) (bool, string)) *MockICasServiceValidatePlainTextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ValidateTicket mocks base method.
func (m *MockICasService) ValidateTicket(ctx context.Context, ticket, service string) (*domain.CasValidationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateTicket", ctx, ticket, service)
	ret0, _ := ret[0].(*domain.CasValidationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateTicket indicates an expected call of ValidateTicket.
func (mr *MockICasServiceMockRecorder) ValidateTicket(ctx, ticket, service any) *MockICasServiceValidateTicketCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateTicket", reflect.TypeOf((*MockICasService)(nil).ValidateTicket), ctx, ticket, service)
	return &MockICasServiceValidateTicketCall{Call: call}
}

// MockICasServiceValidateTicketCall wrap *gomock.Call
type MockICasServiceValidateTicketCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockICasServiceValidateTicketCall) Return(arg0 *domain.CasValidationResult, arg1 error) *MockICasServiceValidateTicketCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockICasServiceValidateTicketCall) Do(f func(context.Context, string, string) (*domain.CasValidationResult, error)) *MockICasServiceValidateTicketCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockICasServiceValidateTicketCall) DoAndReturn(f func(context.Context, string, string) (*domain.CasValidationResult, error)) *MockICasServiceValidateTicketCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
