// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Duke1616/eiam/internal/repository/cache (interfaces: IOidcCache)
//
// Generated by this command:
//
//	mockgen -package=cachemocks -destination=./internal/repository/cache/mocks/oidc.mock.go github.com/Duke1616/eiam/internal/repository/cache IOidcCache
//

// Package cachemocks is a generated GoMock package.
package cachemocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockIOidcCache is a mock of IOidcCache interface.
type MockIOidcCache struct {
	ctrl     *gomock.Controller
	recorder *MockIOidcCacheMockRecorder
	isgomock struct{}
}

// MockIOidcCacheMockRecorder is the mock recorder for MockIOidcCache.
type MockIOidcCacheMockRecorder struct {
	mock *MockIOidcCache
}

// NewMockIOidcCache creates a new mock instance.
func NewMockIOidcCache(ctrl *gomock.Controller) *MockIOidcCache {
	mock := &MockIOidcCache{ctrl: ctrl}
	mock.recorder = &MockIOidcCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOidcCache) EXPECT() *MockIOidcCacheMockRecorder {
	return m.recorder
}

// DeleteApplication mocks base method.
func (m *MockIOidcCache) DeleteApplication(ctx context.Context, clientID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteApplication", ctx, clientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteApplication indicates an expected call of DeleteApplication.
func (mr *MockIOidcCacheMockRecorder) DeleteApplication(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApplication", reflect.TypeOf((*MockIOidcCache)(nil).DeleteApplication), ctx, clientID)
}

// DeleteRefreshToken mocks base method.
func (m *MockIOidcCache) DeleteRefreshToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshToken indicates an expected call of DeleteRefreshToken.
func (mr *MockIOidcCacheMockRecorder) DeleteRefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshToken", reflect.TypeOf((*MockIOidcCache)(nil).DeleteRefreshToken), ctx, token)
}

// DeleteUserRefreshTokens mocks base method.
func (m *MockIOidcCache) DeleteUserRefreshTokens(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserRefreshTokens", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserRefreshTokens indicates an expected call of DeleteUserRefreshTokens.
func (mr *MockIOidcCacheMockRecorder) DeleteUserRefreshTokens(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserRefreshTokens", reflect.TypeOf((*MockIOidcCache)(nil).DeleteUserRefreshTokens), ctx, userID)
}

// GetAndDelAuthCodeContext mocks base method.
func (m *MockIOidcCache) GetAndDelAuthCodeContext(ctx context.Context, code string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAndDelAuthCodeContext", ctx, code)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAndDelAuthCodeContext indicates an expected call of GetAndDelAuthCodeContext.
func (mr *MockIOidcCacheMockRecorder) GetAndDelAuthCodeContext(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAndDelAuthCodeContext", reflect.TypeOf((*MockIOidcCache)(nil).GetAndDelAuthCodeContext), ctx, code)
}

// GetAndDelConsentContext mocks base method.
func (m *MockIOidcCache) GetAndDelConsentContext(ctx context.Context, consentID string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAndDelConsentContext", ctx, consentID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAndDelConsentContext indicates an expected call of GetAndDelConsentContext.
func (mr *MockIOidcCacheMockRecorder) GetAndDelConsentContext(ctx, consentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAndDelConsentContext", reflect.TypeOf((*MockIOidcCache)(nil).GetAndDelConsentContext), ctx, consentID)
}

// GetApplication mocks base method.
func (m *MockIOidcCache) GetApplication(ctx context.Context, clientID string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApplication", ctx, clientID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApplication indicates an expected call of GetApplication.
func (mr *MockIOidcCacheMockRecorder) GetApplication(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApplication", reflect.TypeOf((*MockIOidcCache)(nil).GetApplication), ctx, clientID)
}

// GetConsentContext mocks base method.
func (m *MockIOidcCache) GetConsentContext(ctx context.Context, consentID string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsentContext", ctx, consentID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsentContext indicates an expected call of GetConsentContext.
func (mr *MockIOidcCacheMockRecorder) GetConsentContext(ctx, consentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsentContext", reflect.TypeOf((*MockIOidcCache)(nil).GetConsentContext), ctx, consentID)
}

// GetOrSetClusterSigningKey mocks base method.
func (m *MockIOidcCache) GetOrSetClusterSigningKey(ctx context.Context, keyID string, generateFn func() (string, error)) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrSetClusterSigningKey", ctx, keyID, generateFn)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrSetClusterSigningKey indicates an expected call of GetOrSetClusterSigningKey.
func (mr *MockIOidcCacheMockRecorder) GetOrSetClusterSigningKey(ctx, keyID, generateFn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrSetClusterSigningKey", reflect.TypeOf((*MockIOidcCache)(nil).GetOrSetClusterSigningKey), ctx, keyID, generateFn)
}

// GetRefreshToken mocks base method.
func (m *MockIOidcCache) GetRefreshToken(ctx context.Context, token string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshToken", ctx, token)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshToken indicates an expected call of GetRefreshToken.
func (mr *MockIOidcCacheMockRecorder) GetRefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshToken", reflect.TypeOf((*MockIOidcCache)(nil).GetRefreshToken), ctx, token)
}

// IsTokenRevoked mocks base method.
func (m *MockIOidcCache) IsTokenRevoked(ctx context.Context, token string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTokenRevoked", ctx, token)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTokenRevoked indicates an expected call of IsTokenRevoked.
func (mr *MockIOidcCacheMockRecorder) IsTokenRevoked(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTokenRevoked", reflect.TypeOf((*MockIOidcCache)(nil).IsTokenRevoked), ctx, token)
}

// Ping mocks base method.
func (m *MockIOidcCache) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockIOidcCacheMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockIOidcCache)(nil).Ping), ctx)
}

// RevokeToken mocks base method.
func (m *MockIOidcCache) RevokeToken(ctx context.Context, token string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", ctx, token, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockIOidcCacheMockRecorder) RevokeToken(ctx, token, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockIOidcCache)(nil).RevokeToken), ctx, token, ttl)
}

// SaveApplication mocks base method.
func (m *MockIOidcCache) SaveApplication(ctx context.Context, clientID string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveApplication", ctx, clientID, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveApplication indicates an expected call of SaveApplication.
func (mr *MockIOidcCacheMockRecorder) SaveApplication(ctx, clientID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveApplication", reflect.TypeOf((*MockIOidcCache)(nil).SaveApplication), ctx, clientID, data)
}

// SaveAuthCodeContext mocks base method.
func (m *MockIOidcCache) SaveAuthCodeContext(ctx context.Context, code string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAuthCodeContext", ctx, code, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAuthCodeContext indicates an expected call of SaveAuthCodeContext.
func (mr *MockIOidcCacheMockRecorder) SaveAuthCodeContext(ctx, code, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAuthCodeContext", reflect.TypeOf((*MockIOidcCache)(nil).SaveAuthCodeContext), ctx, code, data)
}

// SaveConsentContext mocks base method.
func (m *MockIOidcCache) SaveConsentContext(ctx context.Context, consentID string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveConsentContext", ctx, consentID, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveConsentContext indicates an expected call of SaveConsentContext.
func (mr *MockIOidcCacheMockRecorder) SaveConsentContext(ctx, consentID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveConsentContext", reflect.TypeOf((*MockIOidcCache)(nil).SaveConsentContext), ctx, consentID, data)
}

// SaveRefreshToken mocks base method.
func (m *MockIOidcCache) SaveRefreshToken(ctx context.Context, token string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRefreshToken", ctx, token, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRefreshToken indicates an expected call of SaveRefreshToken.
func (mr *MockIOidcCacheMockRecorder) SaveRefreshToken(ctx, token, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRefreshToken", reflect.TypeOf((*MockIOidcCache)(nil).SaveRefreshToken), ctx, token, data)
}

// TrackUserRefreshToken mocks base method.
func (m *MockIOidcCache) TrackUserRefreshToken(ctx context.Context, userID, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackUserRefreshToken", ctx, userID, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackUserRefreshToken indicates an expected call of TrackUserRefreshToken.
func (mr *MockIOidcCacheMockRecorder) TrackUserRefreshToken(ctx, userID, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackUserRefreshToken", reflect.TypeOf((*MockIOidcCache)(nil).TrackUserRefreshToken), ctx, userID, token)
}
