// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Duke1616/eiam/internal/repository/cache (interfaces: IResourceCache)
//
// Generated by this command:
//
//	mockgen -package=cachemocks -destination=./mocks/resource.mock.go github.com/Duke1616/eiam/internal/repository/cache IResourceCache
//

// Package cachemocks is a generated GoMock package.
package cachemocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eiam/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIResourceCache is a mock of IResourceCache interface.
type MockIResourceCache struct {
	ctrl     *gomock.Controller
	recorder *MockIResourceCacheMockRecorder
	isgomock struct{}
}

// MockIResourceCacheMockRecorder is the mock recorder for MockIResourceCache.
type MockIResourceCacheMockRecorder struct {
	mock *MockIResourceCache
}

// NewMockIResourceCache creates a new mock instance.
func NewMockIResourceCache(ctrl *gomock.Controller) *MockIResourceCache {
	mock := &MockIResourceCache{ctrl: ctrl}
	mock.recorder = &MockIResourceCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIResourceCache) EXPECT() *MockIResourceCacheMockRecorder {
	return m.recorder
}

// GetAPI mocks base method.
func (m *MockIResourceCache) GetAPI(ctx context.Context, service, method, path string) (domain.API, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAPI", ctx, service, method, path)
	ret0, _ := ret[0].(domain.API)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAPI indicates an expected call of GetAPI.
func (mr *MockIResourceCacheMockRecorder) GetAPI(ctx, service, method, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAPI", reflect.TypeOf((*MockIResourceCache)(nil).GetAPI), ctx, service, method, path)
}

// InvalidateServiceAPIs mocks base method.
func (m *MockIResourceCache) InvalidateServiceAPIs(ctx context.Context, service string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateServiceAPIs", ctx, service)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateServiceAPIs indicates an expected call of InvalidateServiceAPIs.
func (mr *MockIResourceCacheMockRecorder) InvalidateServiceAPIs(ctx, service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateServiceAPIs", reflect.TypeOf((*MockIResourceCache)(nil).InvalidateServiceAPIs), ctx, service)
}

// SetAPI mocks base method.
func (m *MockIResourceCache) SetAPI(ctx context.Context, service, method, path string, api domain.API) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAPI", ctx, service, method, path, api)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAPI indicates an expected call of SetAPI.
func (mr *MockIResourceCacheMockRecorder) SetAPI(ctx, service, method, path, api any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAPI", reflect.TypeOf((*MockIResourceCache)(nil).SetAPI), ctx, service, method, path, api)
}

// SetEmptyAPI mocks base method.
func (m *MockIResourceCache) SetEmptyAPI(ctx context.Context, service, method, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEmptyAPI", ctx, service, method, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEmptyAPI indicates an expected call of SetEmptyAPI.
func (mr *MockIResourceCacheMockRecorder) SetEmptyAPI(ctx, service, method, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEmptyAPI", reflect.TypeOf((*MockIResourceCache)(nil).SetEmptyAPI), ctx, service, method, path)
}
