// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source=./service.go -package=oidcmocks -destination=./mocks/service.mock.go -typed IOidcService
//

// Package oidcmocks is a generated GoMock package.
package oidcmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eiam/internal/domain"
	oidc "github.com/Duke1616/eiam/internal/service/idp/oidc"
	jose "github.com/go-jose/go-jose/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockIOidcService is a mock of IOidcService interface.
type MockIOidcService struct {
	ctrl     *gomock.Controller
	recorder *MockIOidcServiceMockRecorder
	isgomock struct{}
}

// MockIOidcServiceMockRecorder is the mock recorder for MockIOidcService.
type MockIOidcServiceMockRecorder struct {
	mock *MockIOidcService
}

// NewMockIOidcService creates a new mock instance.
func NewMockIOidcService(ctrl *gomock.Controller) *MockIOidcService {
	mock := &MockIOidcService{ctrl: ctrl}
	mock.recorder = &MockIOidcServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOidcService) EXPECT() *MockIOidcServiceMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockIOidcService) Authorize(ctx context.Context, req oidc.AuthorizeRequest) (*oidc.AuthorizeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", ctx, req)
	ret0, _ := ret[0].(*oidc.AuthorizeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorize indicates an expected call of Authorize.
func (mr *MockIOidcServiceMockRecorder) Authorize(ctx, req any) *MockIOidcServiceAuthorizeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockIOidcService)(nil).Authorize), ctx, req)
	return &MockIOidcServiceAuthorizeCall{Call: call}
}

// MockIOidcServiceAuthorizeCall wrap *gomock.Call
type MockIOidcServiceAuthorizeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIOidcServiceAuthorizeCall) Return(arg0 *oidc.AuthorizeResult, arg1 error) *MockIOidcServiceAuthorizeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIOidcServiceAuthorizeCall) Do(f func(context.Context, oidc.AuthorizeRequest) (*oidc.AuthorizeResult, error)) *MockIOidcServiceAuthorizeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIOidcServiceAuthorizeCall) DoAndReturn(f func(context.Context, oidc.AuthorizeRequest) (*oidc.AuthorizeResult, error)) *MockIOidcServiceAuthorizeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ConfirmConsent mocks base method.
func (m *MockIOidcService) ConfirmConsent(ctx context.Context, consentID string, approved bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmConsent", ctx, consentID, approved)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmConsent indicates an expected call of ConfirmConsent.
func (mr *MockIOidcServiceMockRecorder) ConfirmConsent(ctx, consentID, approved any) *MockIOidcServiceConfirmConsentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmConsent", reflect.TypeOf((*MockIOidcService)(nil).ConfirmConsent), ctx, consentID, approved)
	return &MockIOidcServiceConfirmConsentCall{Call: call}
}

// MockIOidcServiceConfirmConsentCall wrap *gomock.Call
type MockIOidcServiceConfirmConsentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIOidcServiceConfirmConsentCall) Return(arg0 string, arg1 error) *MockIOidcServiceConfirmConsentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIOidcServiceConfirmConsentCall) Do(f func(context.Context, string, bool) (string, error)) *MockIOidcServiceConfirmConsentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIOidcServiceConfirmConsentCall) DoAndReturn(f func(context.Context, string, bool) (string, error)) *MockIOidcServiceConfirmConsentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ExchangeToken mocks base method.
func (m *MockIOidcService) ExchangeToken(ctx context.Context, req domain.TokenRequest, issuerURL string) (*domain.OidcTokenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeToken", ctx, req, issuerURL)
	ret0, _ := ret[0].(*domain.OidcTokenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeToken indicates an expected call of ExchangeToken.
func (mr *MockIOidcServiceMockRecorder) ExchangeToken(ctx, req, issuerURL any) *MockIOidcServiceExchangeTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeToken", reflect.TypeOf((*MockIOidcService)(nil).ExchangeToken), ctx, req, issuerURL)
	return &MockIOidcServiceExchangeTokenCall{Call: call}
}

// MockIOidcServiceExchangeTokenCall wrap *gomock.Call
type MockIOidcServiceExchangeTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIOidcServiceExchangeTokenCall) Return(arg0 *domain.OidcTokenResult, arg1 error) *MockIOidcServiceExchangeTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIOidcServiceExchangeTokenCall) Do(f func(context.Context, domain.TokenRequest, string) (*domain.OidcTokenResult, error)) *MockIOidcServiceExchangeTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIOidcServiceExchangeTokenCall) DoAndReturn(f func(context.Context, domain.TokenRequest, string) (*domain.OidcTokenResult, error)) *MockIOidcServiceExchangeTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetConsentInfo mocks base method.
func (m *MockIOidcService) GetConsentInfo(ctx context.Context, consentID string) (*domain.ConsentInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsentInfo", ctx, consentID)
	ret0, _ := ret[0].(*domain.ConsentInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsentInfo indicates an expected call of GetConsentInfo.
func (mr *MockIOidcServiceMockRecorder) GetConsentInfo(ctx, consentID any) *MockIOidcServiceGetConsentInfoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsentInfo", reflect.TypeOf((*MockIOidcService)(nil).GetConsentInfo), ctx, consentID)
	return &MockIOidcServiceGetConsentInfoCall{Call: call}
}

// MockIOidcServiceGetConsentInfoCall wrap *gomock.Call
type MockIOidcServiceGetConsentInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIOidcServiceGetConsentInfoCall) Return(arg0 *domain.ConsentInfo, arg1 error) *MockIOidcServiceGetConsentInfoCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIOidcServiceGetConsentInfoCall) Do(f func(context.Context, string) (*domain.ConsentInfo, error)) *MockIOidcServiceGetConsentInfoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIOidcServiceGetConsentInfoCall) DoAndReturn(f func(context.Context, string) (*domain.ConsentInfo, error)) *MockIOidcServiceGetConsentInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDiscoveryConfig mocks base method.
func (m *MockIOidcService) GetDiscoveryConfig(ctx context.Context, issuerURL string) domain.OidcDiscovery {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscoveryConfig", ctx, issuerURL)
	ret0, _ := ret[0].(domain.OidcDiscovery)
	return ret0
}

// GetDiscoveryConfig indicates an expected call of GetDiscoveryConfig.
func (mr *MockIOidcServiceMockRecorder) GetDiscoveryConfig(ctx, issuerURL any) *MockIOidcServiceGetDiscoveryConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscoveryConfig", reflect.TypeOf((*MockIOidcService)(nil).GetDiscoveryConfig), ctx, issuerURL)
	return &MockIOidcServiceGetDiscoveryConfigCall{Call: call}
}

// MockIOidcServiceGetDiscoveryConfigCall wrap *gomock.Call
type MockIOidcServiceGetDiscoveryConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIOidcServiceGetDiscoveryConfigCall) Return(arg0 domain.OidcDiscovery) *MockIOidcServiceGetDiscoveryConfigCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIOidcServiceGetDiscoveryConfigCall) Do(f func(context.Context, string) domain.OidcDiscovery) *MockIOidcServiceGetDiscoveryConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIOidcServiceGetDiscoveryConfigCall) DoAndReturn(f func(context.Context, string) domain.OidcDiscovery) *MockIOidcServiceGetDiscoveryConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetJWKS mocks base method.
func (m *MockIOidcService) GetJWKS(ctx context.Context) jose.JSONWebKeySet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJWKS", ctx)
	ret0, _ := ret[0].(jose.JSONWebKeySet)
	return ret0
}

// GetJWKS indicates an expected call of GetJWKS.
func (mr *MockIOidcServiceMockRecorder) GetJWKS(ctx any) *MockIOidcServiceGetJWKSCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJWKS", reflect.TypeOf((*MockIOidcService)(nil).GetJWKS), ctx)
	return &MockIOidcServiceGetJWKSCall{Call: call}
}

// MockIOidcServiceGetJWKSCall wrap *gomock.Call
type MockIOidcServiceGetJWKSCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIOidcServiceGetJWKSCall) Return(arg0 jose.JSONWebKeySet) *MockIOidcServiceGetJWKSCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIOidcServiceGetJWKSCall) Do(f func(context.Context) jose.JSONWebKeySet) *MockIOidcServiceGetJWKSCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIOidcServiceGetJWKSCall) DoAndReturn(f func(context.Context) jose.JSONWebKeySet) *MockIOidcServiceGetJWKSCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUserInfo mocks base method.
func (m *MockIOidcService) GetUserInfo(ctx context.Context, tokenString string) (*domain.OidcUserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", ctx, tokenString)
	ret0, _ := ret[0].(*domain.OidcUserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockIOidcServiceMockRecorder) GetUserInfo(ctx, tokenString any) *MockIOidcServiceGetUserInfoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockIOidcService)(nil).GetUserInfo), ctx, tokenString)
	return &MockIOidcServiceGetUserInfoCall{Call: call}
}

// MockIOidcServiceGetUserInfoCall wrap *gomock.Call
type MockIOidcServiceGetUserInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIOidcServiceGetUserInfoCall) Return(arg0 *domain.OidcUserInfo, arg1 error) *MockIOidcServiceGetUserInfoCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIOidcServiceGetUserInfoCall) Do(f func(context.Context, string) (*domain.OidcUserInfo, error)) *MockIOidcServiceGetUserInfoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIOidcServiceGetUserInfoCall) DoAndReturn(f func(context.Context, string) (*domain.OidcUserInfo, error)) *MockIOidcServiceGetUserInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RevokeToken mocks base method.
func (m *MockIOidcService) RevokeToken(ctx context.Context, token, tokenTypeHint, clientID, clientSecret string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", ctx, token, tokenTypeHint, clientID, clientSecret)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockIOidcServiceMockRecorder) RevokeToken(ctx, token, tokenTypeHint, clientID, clientSecret any) *MockIOidcServiceRevokeTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockIOidcService)(nil).RevokeToken), ctx, token, tokenTypeHint, clientID, clientSecret)
	return &MockIOidcServiceRevokeTokenCall{Call: call}
}

// MockIOidcServiceRevokeTokenCall wrap *gomock.Call
type MockIOidcServiceRevokeTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIOidcServiceRevokeTokenCall) Return(arg0 error) *MockIOidcServiceRevokeTokenCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIOidcServiceRevokeTokenCall) Do(f func(context.Context, string, string, string, string) error) *MockIOidcServiceRevokeTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIOidcServiceRevokeTokenCall) DoAndReturn(f func(context.Context, string, string, string, string) error) *MockIOidcServiceRevokeTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
