// Code generated by eiam permgen. DO NOT EDIT.

package model

import "github.com/Duke1616/eiam/pkg/web/capability"

var (
	// Audit 安全审计 (iam:audit)
	Audit = capability.Model{
		Service: "iam",
		Name:    "audit",
		Group:   "安全审计",
		Scope:   capability.ScopeTenant,
	}
	// Department 部门管理 (iam:department)
	Department = capability.Model{
		Service: "iam",
		Name:    "department",
		Group:   "部门管理",
		Scope:   capability.ScopeTenant,
	}
	// Group 用户分组 (iam:group)
	Group = capability.Model{
		Service: "iam",
		Name:    "group",
		Group:   "用户分组",
		Scope:   capability.ScopeTenant,
	}
	// IdentitySource 身份源管理 (iam:identity_source)
	IdentitySource = capability.Model{
		Service: "iam",
		Name:    "identity_source",
		Group:   "身份源管理",
		Scope:   capability.ScopeSystem,
	}
	// Idp 统一身份提供商 (iam:idp)
	Idp = capability.Model{
		Service: "iam",
		Name:    "idp",
		Group:   "统一身份提供商",
		Scope:   capability.ScopeTenant,
	}
	// Invitation 成员治理 (iam:invitation)
	Invitation = capability.Model{
		Service: "iam",
		Name:    "invitation",
		Group:   "成员治理",
		Scope:   capability.ScopeTenant,
	}
	// Permission 权限管理 (iam:permission)
	Permission = capability.Model{
		Service: "iam",
		Name:    "permission",
		Group:   "权限管理",
		Scope:   capability.ScopeTenant,
	}
	// Policy 策略管理 (iam:policy)
	Policy = capability.Model{
		Service: "iam",
		Name:    "policy",
		Group:   "策略管理",
		Scope:   capability.ScopeTenant,
	}
	// Role 角色管理 (iam:role)
	Role = capability.Model{
		Service: "iam",
		Name:    "role",
		Group:   "角色管理",
		Scope:   capability.ScopeTenant,
	}
	// Tenant 租户管理 (iam:tenant)
	Tenant = capability.Model{
		Service: "iam",
		Name:    "tenant",
		Group:   "租户管理",
		Scope:   capability.ScopeSystem,
	}
	// User 用户管理 (iam:user)
	User = capability.Model{
		Service: "iam",
		Name:    "user",
		Group:   "用户管理",
		Scope:   capability.ScopeTenant,
	}
)
